### ISSUE TITLE
»state-download« icon

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/client_theming#10]
@rullzer what does it do? Download state should be the same as sync. Or what does it signify?

**Comment by rullzer** [comment]
I'll dive into this.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by jancborchardt** [comment]
It's still valid.

**Comment by jancborchardt** [comment]
@rullzer @pfiff45 any news on what this icon is? Since I’m redoing the icons I would like to eliminate this status since it’s very confusing.

**Comment by pfiff45** [comment]
currently not used, was anything planed @rullzer?

**Comment by jancborchardt** [comment]
We resolved the question in https://github.com/nextcloud/client_theming/issues/196#issuecomment-321990107 and the icon is being phased out. Please also review the icons @pfiff45 :)
