### ISSUE TITLE
Update client to 2.3.1

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client_theming#100]
Update client to 2.3.1: https://owncloud.org/changelog/desktop/

And btw, why isn't 2.3.0 even out yet?

**Comment by enoch85** [comment]
cc @rullzer

**Comment by enoch85** [comment]
cc @ivaradi for the Linux client

**Comment by mightyBroccoli** [comment]
Will there even be another windows release?

**Comment by ivaradi** [comment]
@enoch85 I have just pushed the branch for  the 2.3.1 client. The binary packages are in the PPA.

**Comment by enoch85** [comment]
It's in master here as well:https://github.com/nextcloud/client_theming/commit/834f74f4d2479a7a88a0a5bab1aee13a2a2e20e7
