### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by patrikx3** [nextcloud/client_theming#101]
is it working 
sudo add-apt-repository ppa:nextcloud-devs/client
with debian testing repo?
or do i should compile?

**Comment by ivaradi** [comment]
For Debian I recommend the repository created specifically for Debian: 

`deb http://download.opensuse.org/repositories/home:/ivaradi//Debian_8.0/ /`

**Comment by patrikx3** [comment]
hello, how can i find the keys?

```bash
W: GPG error: http://download.opensuse.org/repositories/home:/ivaradi//Debian_8.0  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 97E98EAFE52838E6
E: The repository 'http://download.opensuse.org/repositories/home:/ivaradi//Debian_8.0  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details
```

**Comment by patrikx3** [comment]
never mind i found it, thanks.

**Comment by patrikx3** [comment]
sorry, is it not working with Debian 9?
If so , when is it expected?
In the meantime i use owncloud-client...

**Comment by ivaradi** [comment]
I use the OpenSUSE build service for the Debian packages, and they unfortunately do not support Debian 9 yet. I guess, they will add support when Debian 9 is released.

**Comment by ed0c** [comment]
I can't find the pubkey  97E98EAFE52838E6 ( on mit.edu orf ubuntukey server).
How can i find it ?
Thanks

**Comment by ivaradi** [comment]
The key is at http://download.opensuse.org/repositories/home:/ivaradi/Debian_8.0/Release.key
