### ISSUE TITLE
Build nextcloud client in OSX patch no found

### ISSUE THREAD

**Issue by clouddav** [nextcloud/client_theming#102]
Yesterday I tried to build desktop client with Ubuntu and I got stuck at https://github.com/owncloud/client/issues/5624

Today I am trying to build desktop client with OSX and following command giving me error "no such file or directory found"

git apply <client>/admin/qt/patches/qtbase/*.patch
Please note: Nothing mentioned in the doc what should replace <client>

so I tried
git apply https://github.com/owncloud/client/tree/master/admin/qt/patches/qtbase/*.patch
and
git apply https://github.com/owncloud/client/admin/qt/patches/qtbase/*.patch

I am getting the same error "fatal error no such file or directory"

**Comment by enoch85** [comment]
Why not use the offical PPA?

**Comment by clouddav** [comment]
Can you please share the link.

From last two weeks, I am trying to build a client for windows and osx but no success. 

Following guide also did'nt help
https://github.com/nextcloud/client_theming

**Comment by enoch85** [comment]
> with Ubuntu

@clouddav Isn't this what you want? https://github.com/nextcloud/client_theming#installing-on-ubuntu

**Comment by gerardojaime** [comment]
Does exist another guide to build osx desktop app??, the following guide https://github.com/nextcloud/client_theming  is incomplete...

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
