### ISSUE TITLE
connection closed

### ISSUE THREAD

**Issue by patrikx3** [nextcloud/client_theming#103]
When I got 9000 files, it times out all the time, I always have to pause and resume. Like 100 times. :(
![image](https://cloud.githubusercontent.com/assets/4770180/24084731/340eef2e-0cf0-11e7-95a1-6b87411cc3f6.png)

I guess with Dropbox never had a problem, although this is free.
Though I purchased the Andorid client.

**Comment by eyecreate** [comment]
Having some similar problems. here's some details from logs:

```
04-06 22:04:29:659 0xd06ce0  - client version 2.3.1  Qt 4.8.7 
04-06 22:04:29:659 0xd06ce0 -> SyncEngine finished with ERROR 
04-06 22:04:29:659 0xd06ce0 OO folder slotSyncFinished: result:  3 
04-06 22:04:29:659 0xd06ce0     * owncloud csync thread finished with error 
04-06 22:04:29:660 0xd06ce0 the last 6 syncs failed 
```

**Comment by patrikx3** [comment]
it is also weird because on owncloud it works with debian 9 (i had to use that), in nextcloud doesnt work with debian 9 and nextcloud client the last commit was like 15 days ago, and in owncloud last commit  was 3 days ago.

so they just said nextcloud is better, but the truth is that owncloud has more commites.
should just switch back to owncloud?

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
