### ISSUE TITLE
Unable to find executbales after build

### ISSUE THREAD

**Issue by picardim** [nextcloud/client_theming#106]
HI
i finally managed to run the guide but i can't find the executable files after the sudo make install for windows.

can you assist.

Regards,

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
