### ISSUE TITLE
No Icon in taskbar and Exe-Icon and wrong Icon on Crash-Report

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/client_theming#110]
2.3.0beta1
Windows 10 x64

No Taskbar-Icon
![grafik](https://cloud.githubusercontent.com/assets/11041576/24312518/470a87f4-10d9-11e7-8e46-1fa4ee7245d2.png)

And ".exe"
![grafik](https://cloud.githubusercontent.com/assets/11041576/24312557/71f88a06-10d9-11e7-9241-a4eed6aa8229.png)

For the sent crash report I have no picture

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by Bullnados** [comment]
I dont know if it's a theming issue or not.

**Comment by enoch85** [comment]
It works here, have you tested other computers as well?  

Also, is this just on the beta or on stable versions as well?

**Comment by Bullnados** [comment]
I don't know. I only used beta version. I could tested this on one Windows machine cause all other are Linux computers. 
Then I know how to reproduce crashing the app but now I don't. 
For now I close that issue until I can reproduce the error
