### ISSUE TITLE
give log an universal name so it not confuses with nextcloud users

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/client_theming#112]
I am using the nextcloud server (Debian) and the nextcloud windowsclient. In the local datafolder there are log files named owncloud*
![sc](https://i.imgur.com/25rahjy.png)

To keep it simple and universal just rename it to **`.sync.log`** or someting similar

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
