### ISSUE TITLE
[Nextcloud 2.3.0rc1 (build 4) Mac] Connection closed when file downloaded through web browser

### ISSUE THREAD

**Issue by serge-vk** [nextcloud/client_theming#113]
I have discovered that whenever I download a file into a NextCloud-synced folder through a web browser, that file cannot be synced to NextCloud. When I use Safari, the client reports: `downloaded_file_path: Operation canceled`.
There is nothing in the NextCloud log at this moment and the file in question does not get created on the server. In the web server access log I see:
```
23.16.187.29 - UserName [03/Apr/2017:10:14:25 -0700] "PROPFIND /nextcloud/remote.php/dav/files/UserName/downloaded_file_path.download HTTP/1.1" 207 2165 "-" "
Mozilla/5.0 (Macintosh) mirall/2.3.0rc1 (build 4) (Nextcloud)"
```
The web server error log has:
```
2017/04/03 10:14:22 [info] 72984#101968: *75402 kevent() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: NC_Client_IP_Address, server: NC_Server_Address, request: "PUT /nextcloud/remote.php/dav/files/UserName/downloaded_file_path.download/Info.plist HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "NC_Server_Address"
2017/04/03 10:14:32 [info] 72985#101348: *75464 kevent() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: NC_Client_IP_Address, server: NC_Server_Address, request: "DELETE /nextcloud/remote.php/dav/files/UserName/downloaded_file_path.download HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "NC_Server_Address"
 ```
If I use FireFox, the NextCloud client reports: `downloaded_file_path: Connection closed`. In this case, a zero-length file is created on the server, and there are no relevant messages in the NextCloud log or web server error log. The web server access log has:
```
23.16.187.29 - UserName [03/Apr/2017:09:03:16 -0700] "PUT /nextcloud/remote.php/dav/files/UserName/downloaded_file_path-chunking-2187101482-2-0 HTTP/1.1" 412 3
09 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.0rc1 (build 4) (Nextcloud)"
```
Further on, if I delete such a file locally (it takes only one file deleted even if there are a few giving this error in a folder), then the client magically syncs all the other remaining previously failed files.

This issue is probably related to the way such downloads are done (by first creating a zero-length file and a temporary download file and then moving the downloaded file from the temporary to final name). The same problem was present when I used OwnCloud client as well.
### Client-side configuration:
 OS version: Mac OS X 10.10.5
 Web browsers: FireFox 52.0.1; Safari 10.0.3

### Server-side configuration:
Server OS: FreeBSD 11.0 p8
Web server: Nginx 1.11.10
PHP server: 7.1.2
NextCloud server: 11.0.2 (stable)

**Comment by serge-vk** [comment]
A file does not have to be downloaded through a web browser in order to trigger this behaviour. I am seeing it now when saving relatively large documents (~25 Mb) under a different name in MS Word. It seems that if a file inside a synced folder cannot be created fast enough (it is difficult to quantify the meaning of 'fast enough', though), then the client (possibly, it's an interaction between the client and the server) ends up in a state, in which it is no longer able to synchronise this file. On the server, this file remains with a zero length. 

If this zero-length file is deleted on the server through the web interface, the client is then able to sync the local file normally. The same happens if I delete (or move) the local file from the synced folder and then copy it there again. To be honest, this is quite a disruption of regular workflow, when the web interface must be kept open and these 0-length files removed manually every now and then to unblock the client.

If this is a server problem, I can open an issue in the corresponding repo, but I am unable to figure this out on my own.

**Comment by enoch85** [comment]
As this seems more like a ownCloud bug than a theming issue please report it in the ownCloud repo and close this issue, thanks!

**Comment by serge-vk** [comment]
Hi @enoch85, sorry to take long. I am going through OwnCloud issues and see a few related ones (on one of which I commented), but not quite what I reported here. I will probably open a new one and reference the earlier ones from there.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
