### ISSUE TITLE
No U2F support for desktop client

### ISSUE THREAD

**Issue by kees-closed** [nextcloud/client_theming#114]
> Please report all *not* theming related issues at the moment to https://github.com/owncloud/client

That link does work, ticket created [here](https://github.com/owncloud/client/issues/5680).
Update: Link goes to ownCloud, they don't have U2F support, will reopen this ticket.

### Actual behaviour
I enabled U2F (Yubikey Neo) on my Nextcloud for my user account. Now I can't use the desktop client anymore, only with the Chrome browser.

### Expected behaviour
An option to scan my Yubikey Neo to gain access.
 
### Steps to reproduce
1. Enable U2F addon in Nextcloud
2. In the Personal account menu, enable the U2F option
3. Touch the Yubikey
4. Try to log in with the Nextcloud desktop client

### Environment data
Desktop OS: Fedora 25

Nextcloud client version: nextcloud-client.x86_64 2.2.4-8.fc25

Nextcloud server version: 11.0.2

**Comment by MariusBluem** [comment]
Once you enable U2F with Two Factor U2F, your aplications (for example your Android app or your GNOME app) will need to login using device passwords. To manage it, [know more here](https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices).

**Comment by kees-closed** [comment]
@MariusBluem but how does this contribute to the U2F framework? If someone would sniff this 'device' password, would that person then be able to use it to login from another device? Because then the level of security isn't improved at all... Then I'm still vulnerable for password hijacking if two-factor authentication doesn't come into play with these device passwords (one-factor authentication).
