### ISSUE TITLE
where is the 2.3.1 binary?

### ISSUE THREAD

**Issue by tessus** [nextcloud/client_theming#117]
I'm a bit puzzled. There was a 2.3.1 release 16 days ago. There is no package anywhere. Not at https://download.nextcloud.com/desktop/prereleases/Mac/ and not at https://download.nextcloud.com/desktop/releases/Mac/Installer/

I'm sorry, I don't have 180 GB free storage on my 250 GB SSD to compile QT as decribed in the README.md, thus I'm depending on binaries.

Can someone please make a 2.3.1 binary for OSX?

**Comment by enoch85** [comment]
Same for Windows. 

Though it seems that you can use the snaps on Mac OS: http://askubuntu.com/questions/791395/is-snap-portable-across-other-unix-example-macos and I think there is something ging on with the snaps here as well: https://github.com/nextcloud/client_theming/pull/115

@nickvergessen Any ETA on building the clients for Windows and Mac?

**Comment by nickvergessen** [comment]
I'm not the person to ping for clients...

**Comment by enoch85** [comment]
Sorry I meant @rullzer

**Comment by menaceone** [comment]
Hmm, one month since the release of 2.3.1 and on [https://nextcloud.com/install/#install-clients](url) you still get 2.2.4. 
There is also no update notification within the client. 
I'm not in a hurry to update, just wondering why this is as it is?

greetings

**Comment by tessus** [comment]
I think they stopped releasing binaries for macOS. I am using the owncloud client for my nextcloud installation.

**Comment by reinholdaudials** [comment]
Someone knows if the SSL issue is finally fixed https://github.com/nextcloud/client_theming/issues/13 ? As long as this is not fixed and the client won't work with modern web servers I think it does not make any sense to officially release a new version.

**Comment by fhemberger** [comment]
@reinholdaudials Ah, looks like I ran into that issue with 2.2.41, https://download.nextcloud.com/desktop/prereleases/Mac/Nextcloud-2.3.0.4rc1.pkg seems to have fixed it for me.

**Comment by reinholdaudials** [comment]
Yeah, that fixes it. Very great. Thank you.

**Comment by menaceone** [comment]
@tessus there is also no binary for Windows, so there is no latest binary at all.

**Comment by stffabi** [comment]
For windows the installer could be found here https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.3.1.8-setup.exe

**Comment by enoch85** [comment]
Hmm, why isn't that linked on the downloads page...? Will make a PR.

**Comment by stffabi** [comment]
@enoch85 that would be great. Unfortunately I wasn't able to find the OSX binaries for 2.3.1

**Comment by enoch85** [comment]
Ok, Windows is already fixed but not pushed yet. Why is that @jospoortvliet? 

https://github.com/nextcloud/nextcloud.com/blob/master/strings.php#L9

**Comment by enoch85** [comment]
Yup that's exactly what I mean. Let's got with that. 

` . <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh | pv)`

gives `12,9KiB 0:00:00 [ 118KiB/s] [   <=>`

**Comment by enoch85** [comment]
But no... it's only for downloading the curl, the the actual loading takes a bit longer.

`pv` in combination with something else maybe?

**Comment by enoch85** [comment]
```
root@cloud:~# bash -x /var/scripts/nextcloud_update.sh 
+ true
+ NC_UPDATE=1
+ . /dev/fd/63
++ curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh
++ pv
12,9KiB 0:00:01 [ 6,8KiB/s] [   <=>                                                                                                                                                                               ]
++ true
++ SCRIPTS=/var/scripts
++ NCPATH=/var/www/nextcloud
++ HTML=/var/www
++ NCDATA=/var/ncdata
++ SNAPDIR=/var/snap/spreedme
++ GPGDIR=/tmp/gpg
++ BACKUP=/var/NCBACKUP
+++ lsb_release -sd
+++ cut -d ' ' -f 2
++ DISTRO=16.04.2
+++ grep -ic Ubuntu /etc/issue.net
++ OS=1
++ '[' '!' -z '' ']'
+++ cut -d : -f 1
+++ grep UP
+++ awk '{print $2,$9}'
+++ ip -o link show
++ IFACE2='ens160
docker0'
```

As you can see here it only runs `pv` on the download, and *then* run the variables. I want to have a progress bar for loading the variables.

**Comment by enoch85** [comment]
Hehe, wrong issue. :$

**Comment by enoch85** [comment]
This is now fixed

**Comment by enoch85** [comment]
Sorry, only for Windows. Mac is not updated yet... cc @jospoortvliet

**Comment by tessus** [comment]
this is a joke. the owncloud client has already version 2.3.2 for mac available. I'm closing this, since nobody gives a fuck about the nextcloud client for macos.

Yes, please berate me for the choice of my words instead of releasing a binary.

**Comment by tessus** [comment]
no, seriously, I closed it because it's not a bug and I just wanted to know what happened to the binary. after 30 days and no answer, plus a much newer owncloud client available, it makes no sense to leave this ticket open.

**Comment by enoch85** [comment]
cc @rullzer @jospoortvliet --^ Where is the answer?

**Comment by enoch85** [comment]
Should be built thoug... https://github.com/nextcloud/client_theming/commit/b80f32d79164f19f7e4844fd4f901ed6f442f0b5

**Comment by Escubaer** [comment]
I just use the ownCloud Client on my Mac. And also looking into ownCloud 10.0 some interesting stuff I will likely get used to and migrate if its not showing up in Nextcloud, soon.
