### ISSUE TITLE
NO_PUBKEY 60EE47FBAD3DD469 when installing PPA

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client_theming#118]
@ivaradi I get this error when trying to install your PPA. Can you please have a look?

```
root@daniel-pc:~# apt update 
Hit:1 http://www.mirrorservice.org/sites/packages.linuxdeepin.com/deepin unstable InRelease
Hit:3 http://repository.spotify.com stable InRelease
Get:2 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu zesty InRelease [15.9 kB]
Err:2 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu zesty InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 60EE47FBAD3DD469
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu zesty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 60EE47FBAD3DD469
E: The repository 'http://ppa.launchpad.net/nextcloud-devs/client/ubuntu zesty InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Deepin 15.3** (Debian based)

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/client_theming/issues/101

**Comment by ivaradi** [comment]
The key is available here: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x60EE47FBAD3DD469 (E.g. you can copy the parts between the "BEGIN/END PGP PUBLIC KEY BLOCK" lines - including those - into a file and then add it to your system using `apt-key add`.)

However, the key should be added automatically by `add-apt-repository`. Did you use that command? Did it print some errors?

That said, this key is provided by Launchpad which uses its private counterpart to sign the packages. So if it is unavailable at times, it must some outage of their servers. However, it seems to work well usually, so it should not happen too often.

**Comment by enoch85** [comment]
@ivaradi Ok thanks! Not tested this yet, but I'll try to add it later.

**Comment by stefan2904** [comment]
> An error occurred during a connection to keyserver.ubuntu.com:11371. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by ivaradi** [comment]
It is most likely some temporary outage of the Ubuntu keyserver and/or a misconfiguration on your machine. It is beyond our control.

**Comment by enoch85** [comment]
Yup, noticed an outage today.
