### ISSUE TITLE
Release the Linux Client with Travis

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client_theming#119]
Just noticed that you can release to Launchpad with Travis: https://docs.travis-ci.com/user/deployment/launchpad/

Something to implement @ivaradi?

**Comment by ivaradi** [comment]
I checked out this feature of releasing to Launchpad. What it does is to ask Launchpad to synchronize its copy of the repository with the GitHub one. Launchpad can be given so-called build recipes which can then build source packages and upload them to a PPA, which can then build the binary packages.

However, it does not work with submodules, so it is not really useful for us at the moment.

So, I implemented the build and source package upload in Travis itself, in pull request #133. See some more explanation there.

**Comment by enoch85** [comment]
This is somewhat done now. Travis is at least implemented. Well done @ivaradi :)
