### ISSUE TITLE
Cant sync anymore with 2.3.1

### ISSUE THREAD

**Issue by Dragnell87** [nextcloud/client_theming#120]
After update to the latest version i am unable to sync anymore, all other users using the 2.2.4 version can sync just fine. 

From the server i get "PROPFIND /remote.php/dav/files/user HTTP/1.1" 404 1782 
i also notice that 2.2.4 make the request different, like this: 
2.2.4
PROPFIND /remote.php/webdav/
and the 
2.3.1
PROPFIND /remote.php/dav/files/user

Any suggestion ?

**Comment by cmtonkinson** [comment]
I have v2.3.1 and it is sending `PROPFIND /remote.php/webdav/`.

**Comment by Dragnell87** [comment]
How can i change the profind parameter ?
whend i use  nextcloudcmd --davpath remote.php/webdav/ /home/user/Nextcloud https://server
all seems fine .

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
