### ISSUE TITLE
Account info lost after exiting the client (Win 10)

### ISSUE THREAD

**Issue by 747** [nextcloud/client_theming#121]
Client: v2.2.4
OS: Windows 10 x64 (Anniversary Update)
Server: v11.0.2

The client seems to fail to store my config persistently, so that every time when I restart the program I have to re-enter my server URL, user name, sync settings etc.
I believe it was not the case when I was using the OwnCloud client.

**Comment by neffo** [comment]
I am seeing the same issue on Ubuntu 17.04 with client version 2.3.1 (from official PPA). Seems to be intermittent with me. Unsure if the config file is wiped clear, corrupted or deleted.

**Comment by powerpaul17** [comment]
Can be related to [https://github.com/owncloud/client/issues/5628#issuecomment-287728645](https://github.com/owncloud/client/issues/5628#issuecomment-287728645)

**Comment by enoch85** [comment]
This is an ownCloud issue, please report it in their repo. Thanks!

**Comment by 747** [comment]
@enoch85 Hi, can you give the reason why you think it's an ownCloud issue? In my env, only Nextcloud had the problem and ownCloud didn't (as I said in my initial description).

I tried reinstalling ownCloud just in case, and it worked as well as it had been.

That said, now I grabbed the v2.3.1 client and log in through app password, then the problem no more happens, so thank you guys. (Was auto-update not ready yet in v2.2.x?)
