### ISSUE TITLE
Icon overlay display sharing and error status

### ISSUE THREAD

**Issue by ghost** [nextcloud/client_theming#122]
Hi!

Since this is the first time i am reporting something here via github i kindly ask for your understanding and help to point me in the right direction if this post doesn't belong in this area.

Today there are, by my knowledge, two different overlay icons that show sync status on desktops, managed by the sync client. The blue one showing the file/folder has not been synced and the green one showing the file/folder is in sync.

By adding two more icons the user may get a more complete experience.
- A red one, illustrating there was an error during sync or user interaction is required to complete.
- Add variants of the green and blue ones illustrating the file/folder has been shared. Two examples below:

![shared](https://cloud.githubusercontent.com/assets/27644286/25074380/bdb25d82-22f9-11e7-94fb-bce9dc947399.PNG)
![shared2](https://cloud.githubusercontent.com/assets/27644286/25074407/57c878fc-22fa-11e7-9f29-8ecb7ae112c9.PNG)

Regards

## EDIT 2017-04-21

I now see this seems to be an error that originate from the owncloud client. I'm running client version 2.2.4 (build 2) which seems to be the latest stable version available for download.

### Expected behavior:
When the folder has shared status, ie. shared by link or to other users on the same server I expect this overlay icon to be used. 
![image](https://cloud.githubusercontent.com/assets/27644286/25285979/6f0807c4-26bc-11e7-8503-bd20502b175b.png)

### Actual behavior:
No differences between folders that is shared and folders that is shared are shown by the overlay icon. Below there's some screenshots provided.

### Common info:
Nextcloud version: 11
Client Version: 2.2.4 (build 2) - seems to be latest stable version available for download from https://nextcloud.com/install/#install-clients

### Screenshots
**From within Windows 7:**
![image](https://cloud.githubusercontent.com/assets/27644286/25286087/d02765ae-26bc-11e7-8609-549e1c93219f.png)

**From web interface:**
![image](https://cloud.githubusercontent.com/assets/27644286/25286116/e2749538-26bc-11e7-90af-0cf7e55906e1.png)

**Comment by ghost** [comment]
Anyone who know something about this?

**Comment by enoch85** [comment]
> I now see this seems to be an error that originate from the owncloud client. I'm running client version 2.2.4 (build 2) which seems to be the latest stable version available for download.

Closing
