### ISSUE TITLE
2.3.1 Dosen't work as expected with Zesty

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client_theming#123]
@ivaradi I just installed Ubuntu 17.04 and for some strange reason I can't sync via my domain address anymore, IP works fine though. It worked fine in 16.04.2

Is this a Client error or is it on my end, what do you think?

**Comment by ivaradi** [comment]
Can you access the server with a browser using the domain address?

**Comment by enoch85** [comment]
@ivaradi Yes

**Comment by ivaradi** [comment]
Then it is more likely a problem with the client, or at least with the libraries it uses (e.g. Qt), after all the same source code is used on all Ubuntu variants, and it works on others... Or it may be just some setting somewhere...

I guess I will install a Zesty in a VM (I do not want to upgrade my main system yet) and try to do some debugging, when my time allows and if the problem appears for me as well.

**Comment by enoch85** [comment]
@ivaradi Thanks! To be sure to work on the same system I'm on Ubuntu 17.04 Budgie.

**Comment by enoch85** [comment]
Sorry @ivaradi I rebooted and it's working now for some reason.
