### ISSUE TITLE
flatpak version of NextCloud client

### ISSUE THREAD

**Issue by rugk** [nextcloud/client_theming#125]
As https://github.com/owncloud/client/issues/5716 failed, I'll better repeat my issue here. Your issue template of "not theming issues" could be clarified a bit…

----

Please create a flatpak version of the NextCloud client, so one can use this on Linux instead of having to built the sources.

**Comment by mightyBroccoli** [comment]
I am not quite sure what you are trying to archive here. There are so many possible ways to install this app on all kind of different distros. There are

- Debian repository
- Ubuntu repository
- Suse
- archlinux AUR
- Fedora
- and if you have such an uncommon distro use the snap version.

I am pretty sure I even missed a ton of possibilities.

But my main point is what are you trying to archive here? Should the developers invest even more time into dozens and dozens of Distribution methods to cower even the smallest distros with a special installation way, when there is already a possible way to archive the same goal? I am not sure why that would solve any problem.

**Comment by rugk** [comment]
You can summarize them as "disto packages" and as one does not have multiple distros running at the same time for one distro there is basically 1 way to install it. Not multiple ones…
And if there would be packages it would be nice, but
* there are [no Debian packages](https://packages.debian.org/search?searchon=names&keywords=nextcloud)
* some [Ubuntu PPAs](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client)
* and the only other official packages are from [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=nextcloud-client)

These are also linked on the NextCloud download page.

Multiple issues document how user cannot install the client because it is only available in source code form: https://github.com/nextcloud/client_theming/issues/117 (suggesting snaps), https://github.com/nextcloud/client_theming/issues/61 (also suggesting another static format AppImage) and last, but not least https://github.com/nextcloud/client_theming/issues/32 with 40 comments(!) and 21 :+1: on the first comment…
This clearly documents the need for such a thing.

> Should the developers invest even more time into dozens and dozens of Distribution methods

Good joke. Flatpak is actually intended to solve this problem as it can run on many platforms without another packaging or so needed. And if you think players like Debian, GNOME or so are small, I don't know what to say anymore…

**Comment by mightyBroccoli** [comment]
I am running nextcloud client on 5 debian maschine and did not have any problems. Most of the time somebody has problems with the installation, the repository is not the fault.
I know thats not a good valid point but introducing yet another packaging solution isnt either.

**Comment by rugk** [comment]
But there is no package in the official Debian repo. Where did you got the client from?

**Comment by mightyBroccoli** [comment]
There are even 2 possible ways
First @ivaradi s Debian packaging from suse
http://download.opensuse.org/repositories/home:/ivaradi//Debian_8.0/

and @morph027 repository
https://repo.morph027.de/#debian

I personally use the first one on my debian Laptop

**Comment by rugk** [comment]
Thanks for the links.

**Comment by piotr-dobrogost** [comment]
*Flatpak is actually intended to solve this problem (...)*
Obligatory https://xkcd.com/927/

**Comment by rugk** [comment]
Without clicking in the link (and not remembering xkcd numbers) I know what you're linking to. But hey, tell this the snap people.😉
Nevertheless they both can help here.

**Comment by probonopd** [comment]
> Please create a flatpak version of the NextCloud client, so one can use this on Linux instead of having to built the sources.

Have you tried [the AppImage](https://github.com/nextcloud/client_theming/releases)? If yes, why is it not suitable for you? If no, why not?

**Comment by rugk** [comment]
As you can see from the comments in that issue I had problems getting the app image. In the end I got one from the the Travis built or so, but it did not work.
Anyway thus is not a proper solution. A good built (no master whether .deb which actually works with Debian 8 instead of the OpenSuse one which requires a more recent keystore/seahorse or so, or a snap or flatpak) should be provided on the main download site and not in some pesky places.

**Comment by probonopd** [comment]
> As you can see from the comments in that issue I had problems getting the app image. 

The AppImage is linked on the GitHub Releases page:
https://github.com/nextcloud/client_theming/releases
I could download it with no issues.

> In the end I got one from the the Travis built or so, but it did not work.

Please elaborate on "it did not work". This needs to be fixed.

> Anyway thus is not a proper solution. A good built (no master whether .deb which actually works with Debian 8 instead of the OpenSuse one which requires a more recent keystore/seahorse or so, or a snap or flatpak)

The AppImage should run on most Linux distributions. If you have issues, let us debug them.

> should be provided on the main download site and not in some pesky places.

Agree :-)
https://github.com/nextcloud/client_theming/issues/32#issuecomment-272611639

**Comment by rugk** [comment]
>The AppImage is linked on the GitHub Releases page

Ah that's a newer release. v2.3.1 was difficult to get.

I'll try it again and probably open new issues…

**Comment by rugk** [comment]
Also the releases should be signed and a checksum (SHA-256) should be provided…

current one for comparison: 71fff5b524c9934474280d230786439cb5565100954195f096e207bc4ba70a36

**Comment by rugk** [comment]
see https://github.com/nextcloud/client_theming/issues/127

**Comment by enoch85** [comment]
Guys, why develop a flatpak when we already have snaps available?

**Comment by adityashah1212** [comment]
Well for one, snap images can be notoriously huge, (was the case couple of months ago atleast) and it is a centralized distribution mechanism which is completely controlled by Canonical, no source code released for the server end side, and you need to sign a Contributors Licence Agreement (Why? Can't understand, when the app itself is opensource).

**Comment by probonopd** [comment]
@adityashah1212 these concerns should be addressed by the AppImage.

**Comment by rugk** [comment]
Wow really, never knew that? Then maybe rather use flatpak. There you can setup your own repo.

An AppImage has the disadvantage that it is not sandboxed.

**Comment by adityashah1212** [comment]
I want to work on this, but everytime I try to compile qt5-webkit my computer completely freezes, any ideas why?

**Comment by adityashah1212** [comment]
I also forgot mention above that snapd-confine (responsible for snap sandbox) relies on apparmor so distributions without apparmor run snap in "dev-mode"; meaning no sandbox. Flatpak uses bubblewrap for confinement, which relies on user namespaces if supported else can be compiled with setuid. Hence either using user namespaces or setuid flatpaks will always be sandboxed.

**Comment by juliusknorr** [comment]
I have started a flatpak version of the sync client and submitted it to flathub. Testing/feedback is very welcome:

https://github.com/flathub/flathub/pull/76

**Comment by juliusknorr** [comment]
The Nextcloud flatpak is now available on flathub. Feel free to give it a try:

```
flatpak install --from https://flathub.org/repo/appstream/org.nextcloud.Nextcloud.flatpakref
```

The repo for building the flatpak is located here. https://github.com/flathub/org.nextcloud.Nextcloud
