### ISSUE TITLE
Plugin for Dolphin file manager

### ISSUE THREAD

**Issue by viggy96** [nextcloud/client_theming#130]
I'm pretty sure there used to be a plugin for the Dolphin file manager, but its not available now. Is it not available, or is it still in the works?

**Comment by ivaradi** [comment]
The latest version in the PPA (if you are using Ubuntu) should contain support for Dolphin. Please, give it a try and let me know your results.

**Comment by Gerii** [comment]
Seems to work fine at least for me (even though the packages do not show up on Launchpad for some reason). Thanks for packaging this!

**Comment by ivaradi** [comment]
Launchpad lists only the source packages on the PPA's main page. But a single source package can produce multiple binary ones. If you select the "View package details" link (https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client/+packages) and you open one of the "nextcloud-client" packages, you can see the Dolphin plugin listed (https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client/+sourcepub/7800621/+listing-archive-extra).

Anyway, thanks for the feedback. I am now closing this issue hoping that it works for @viggy96 and all other users.
