### ISSUE TITLE
.desktop file unbelievably large

### ISSUE THREAD

**Issue by inputsh** [nextcloud/client_theming#135]
### Expected behaviour

For the `.desktop` file to just have 10 necessary lines + translations.

### Actual behaviour

The `.desktop` file contains 800+ lines. First 10 lines are the usual desktop entry lines, followed by

    # Translations
    
    
    # Translations
    ...

So, one comment, two blank lines. This goes all the way down to the line 805, which is then followed by the actual translations.

I believe this has something to do with the theming, since this file is directly impacted by the theming, hence, I'm submitting it here, and not to the owncloud repository.

System info:

* OS: Ubuntu (GNOME) 17.04
* Desktop version: 2.3.1
* Server version: 11.0.2
* Installation method: PPA

**Comment by hanzei** [comment]
Where is the `.desktop` file located?

**Comment by inputsh** [comment]
On a system: in `/usr/share/applications`. In this repository: I have no clue how it gets generated.

**Comment by ivaradi** [comment]
This file comes from the ownCloud client, where it is of essentially the same size (see https://github.com/owncloud/client/blob/master/mirall.desktop.in). Only the contents are changed: during building the application name strings are set to either "ownCloud" or "Nextcloud", depending on the theming

I think this issue should be reported to ownCloud instead and this one should be closed.

**Comment by inputsh** [comment]
Closing. Reported here: https://github.com/owncloud/client/issues/5767
