### ISSUE TITLE
Help with compiling and customizing?

### ISSUE THREAD

**Issue by JayBenjamin** [nextcloud/client_theming#144]
I've customized the web side of thinks, but am finding out that customizing and compiling the pc client is a bit challenging for my skill level. Can someone share step by step docs or a vid that's geared towards a newb

**Comment by hanzei** [comment]
Isn't [this](https://github.com/nextcloud/client_theming#building-on-linux) sufficient enough?

**Comment by JayBenjamin** [comment]
Not for me. I was looking at the Docker info- I installed it, but couldn't work it out. I would imagine Linux would be the same.

**Comment by JayBenjamin** [comment]
I'd be willing to pay someone some nice mother's day gift money to help me out with this and or just do it for me. I'm trying to customize icons and copy, images, and hardcode the server address for my server in there. I need a PC version. I have all the images and icons ready.

**Comment by LukasReschke** [comment]
This would be more something for our forums at help.nextcloud.com

**Comment by JayBenjamin** [comment]
thanks @luiscruz
