### ISSUE TITLE
error while loading shared libraries: libnextcloudsync.so.0

### ISSUE THREAD

**Issue by ghost** [nextcloud/client_theming#15]
nextcloud app won't start (debian 8.0 GNOME) after installing following the instructions.

`nextcloud: error while loading shared libraries: libnextcloudsync.so.0: cannot open shared object file: No such file or directory`

But even running it as SU it won't find libnextcloudsync.so.0

libnextcloudsync files are present in:

`/usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so
/usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so.0
/usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so.2.2.3`

**Comment by dajva** [comment]
Ubuntu (and I assume Debian as well) doesn't have /usr/local/lib/\* paths in the dynamic loader's search path.
Modify `/etc/ld.so.conf.d/x86_64-linux-gnu.conf` by adding the line:
`/usr/local/lib/x86_64-linux-gnu`

Then run:
`sudo ldconfig`

Works for me on Linux Mint 18.

**Comment by greenorca** [comment]
hi...

I'm not much of a build guru, yet I have the same issue on Ubuntu 1604. The make & make install worked well, no errors. I tried above suggestion, but still have the error from the initial remark. As well, the libs are in place as described. Any suggestions?

**Comment by greenorca** [comment]
Good man - works well on Ubuntu 1604!

**Comment by pasbec** [comment]
For me, changing `CMAKE_INSTALL_DIR` to `/usr` instead of the default `/usr/local` for the `cmake` command worked just [fine](https://github.com/nextcloud/client_theming/issues/25/#issuecomment-254232998)

**Comment by ftx** [comment]
Same problem on fedora 24.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
