### ISSUE TITLE
Building on Linux doc: dependencies

### ISSUE THREAD

**Issue by rigrig** [nextcloud/client_theming#16]
The build instructions don't list which dependencies you need to build.
For Debian: ownCloud instructs people to use `apt-get update; apt-get build-dep owncloud-client` after adding the openSUSE repo.
As long as there is no Nextcloud .deb, the instructions here should probably list the actual dependencies?
(If people want to build from source, having the actual list in the instructions seems preferable to me anyway)

From that ownCloud package:

```
Build-Depends: debhelper (>= 9), cmake, sed, doxygen, unzip | bash,
 libsqlite3-dev, python-sphinx | python3-sphinx, libssl-dev,
 libqtwebkit-dev (>= 2.2.0) | libqt5webkit5-dev (>= 2.2.0),
 qtkeychain-dev (>= 0.7.0) | qt5keychain-dev (>= 0.7.0)
```

So possibly something like
`apt-get install debhelper cmake sed doxygen unzip libsqlite3-dev python-sphinx libssl-dev libqt5webkit5-dev qt5keychain-dev`
(that seemed to do the trick on my LMDE system)

**Comment by rullzer** [comment]
Yes fair enough. The thing is this differes a lot per distro.
But I can look into this a bit.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by rigrig** [comment]
Solved: build dependencies for Ubuntu were added to the README in 632badfce47d9d1a9f7e794dedf22bfdcaa2c0f7 and for Debian in 30c87df4b648f32b72964d15eb9cebf77a8827e1

**Comment by enoch85** [comment]
@rigrig Thanks!
