### ISSUE TITLE
Disable update notification

### ISSUE THREAD

**Issue by rugk** [nextcloud/client_theming#166]
When using the system update tool (linux package manager) to update the client, one gets a notification "Version x.y of the NextCloud client is available. Use your system update tool to update."

However, there is no option to disable this check/this notification, because the notification is largely useless. If your distro/package manager has not yet released an update, there is no need to annoy the user with a notification.
And when an update is really available, you can a notification from your system update tool, anyway…

So there should at least be a way to disable it.

**Comment by enoch85** [comment]
@rugk Please post this issue in the ownCloud repo as requested when you created this issue, thanks.

Reason: this is not a theming issue, rather a upstream "issue".

**Comment by rugk** [comment]
Done: https://github.com/owncloud/client/issues/5814
