### ISSUE TITLE
Debian repository should be signed

### ISSUE THREAD

**Issue by cedryc** [nextcloud/client_theming#167]
Hello,
Nextcloud client theming repo for Debian has to be signed:
wget http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/Release.key
apt-key add - < Release.key

Theses lines should be added to the README.md file.

source: https://intux.de/2017/06/nextcloud-client-fuer-debian-9/

Thank for this great app!

**Comment by ivaradi** [comment]
Hello,

you are right. I have added the instructions to install the key (8f3be26c52e565165058bfd2b4c9449b2fcedacd).

**Comment by enoch85** [comment]
Merged
