### ISSUE TITLE
Excessive bandwidth usage

### ISSUE THREAD

**Issue by exander77** [nextcloud/client_theming#171]
I am using:
Nextcloud version 2.2.4
Using Qt 5.7.1
On:
Ubuntu 17.04

I went on vacation, I was like 1h on the internet so far and owcloud ate like 3,5GB from my FUP. There may have been like 10MB of changed files which needed to be synchronized. What the hell nextcloud has been doing? Never had this problem with ownlcoud client.

**Comment by enoch85** [comment]
@exander77 Did you run the ownCloud client and the Nextcloud client side by side, or just the Nextcloud client?

How did you install it?

**Comment by exander77** [comment]
No, I moved compelely to Nextcloud (Server & Client) like half a year ago.

I think I built it from the source.

If this is a common problem, there should be a warning (I thought I will be working on vacation and now I am already out of 3,5GB after a few hours).

**Comment by enoch85** [comment]
This sounds more like a ownCloud problem than a Nextcloud issue. This app is reallt just a "copy" of the ownCloud app with some theming implemented. So I'd suggest that you report this issue on their repo.

Thanks!

**Comment by exander77** [comment]
Owncloud? You mean nextcloud server? I don't see how it can be a server issue. The client is clearly the one doing traffic. Can I debug what the client is actually doing?

**Comment by enoch85** [comment]
When you opened this issue it said:
```
Thanks for reporting issues back to Nextcloud!

Please report all *not* theming related issues at the moment to https://github.com/owncloud/client
```

And as I wrote:

> This app is reallt just a "copy" of the ownCloud app with some theming implemented. So I'd suggest that you report this issue on their repo.

So in other words, please report this issue to ownCloud, this is just a theming repo. :)

About the debugging, use wireshark and inspect the packets maybe?

**Comment by exander77** [comment]
Oh, I understand now.
