### ISSUE TITLE
"Conflicted" items not synching

### ISSUE THREAD

**Issue by CJR2** [nextcloud/client_theming#174]
When 2 users open up the same file
Example: test.txt

and both make changes (ex: MS Excel file) to trigger a version conflict, NextCloud will create a 2nd file to recognize the conflict.
ex: Test_conflict-20170623-100411.txt

**Bug / Issue: This new file does not get synched back to the server.**

The synch back to the server is very important; otherwise 1) the user doesn't know that their info wasn't available to co-workers and 2) user could lose their information / edits when the return back to the base file (text.txt in this instance()

I have looked at the sync-exclude.lst file in the windows client, and unable to find any exclusion within that prohibits the file from being copied to the server.

**Comment by enoch85** [comment]
This is an issue with the syncing client not Nextcloud theming, so please report this issue to the ownCloud client repo: https://github.com/owncloud/client

Thanks!
