### ISSUE TITLE
Introduce Nextcloud client into Debian repositories (like owncloud-client)

### ISSUE THREAD

**Issue by ghost** [nextcloud/client_theming#178]
Would it be possible to rebrand owncloud-client as Nextcloud client and get it into the Debian repositories?

https://packages.debian.org/stretch/owncloud-client

**Comment by juliusknorr** [comment]
That is up to the Debian community, see bug there: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847613

There are already binary packages for Debian as well. You can find more information about those in the forum: https://help.nextcloud.com/t/linux-packages-status/10216

**Comment by ghost** [comment]
This package should be welcome into Debian as long as it adheres to their build policy and somebody commits to maintaining it for the duration of the next stable release.
