### ISSUE TITLE
Win: No autostart of Nextcloud Client at Windows startup

### ISSUE THREAD

**Issue by Siedlerchr** [nextcloud/client_theming#18]
Version 2.2.3 (build 4)  on Windows 7 x64

After uninstalling owncloud client and then installing Netxtcloud client I now have the problem that the client does not load at startup from win.

However, the owncloud Client does it.

**Comment by nickvergessen** [comment]
Works fine here. Can you try to disable the autostart option and reenable it?

**Comment by Siedlerchr** [comment]
I found out that the autostart option is no longer enabled by default when you install the NC client. 
I enabled it manually and it works.

**Comment by nickvergessen** [comment]
Let's keep this open, @rullzer might have a way to fix this.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by Siedlerchr** [comment]
From my point of view it can be closed.

**Comment by enoch85** [comment]
@Siedlerchr Thanks!
