### ISSUE TITLE
Add Artful to Ubuntu releases

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client_theming#180]
Ubuntu 17.10 is named `artful`. We should add that to launchpad.

cc @ivaradi

**Comment by ivaradi** [comment]
Launchpad could compile the package, so I think it can be considered done.

**Comment by enoch85** [comment]
@ivaradi Can you please make the same change to the stable branch?

**Comment by ivaradi** [comment]
There is only the ````master```` branch that we have and we perform deployment from that one only. Do you mean to create a new branch from the time before version 2.3.2 of the client has been imported and modify  the Travis build to deploy from that one as well to the stable Launchpad repository?

Actually, should not the current 2.3.2 beta made a stable version already? I think the client was released quite a long time ago, and they are already at version 2.4.0.

**Comment by enoch85** [comment]
@ivaradi Latest version is 2.3.1: https://owncloud.org/changelog/desktop/

But we can close this. Once beta becomes stable here, the changes will follow. I'm running beta now anyway, works fine. :)
