### ISSUE TITLE
Missing v2.3.2 release for mac

### ISSUE THREAD

**Issue by silsha** [nextcloud/client_theming#187]
The latest macOS binary release seems to be v2.2.4.1 while v2.3.1 came out on 23 march and 2.3.2 3 days ago.

* https://nextcloud.com/install/#install-clients shows the latest stable release would be v2.3.1 but the macOS download button gives you v2.2.4.1.
* This is also the latest version in the directory (https://download.nextcloud.com/desktop/releases/Mac/Installer/)

This problem was already mentioned in #117 by @tessus but it was closed without a fix.

**Comment by silsha** [comment]
Just found [this thread](https://help.nextcloud.com/t/client-v2-3-1-not-available-for-macos/14681) in the nextcloud forums. Latest update from 29 July was
> This is currently in internal testing phase. Just to keep you guys updated.
https://help.nextcloud.com/t/client-v2-3-1-not-available-for-macos/14681/5

**Comment by enoch85** [comment]
@rullzer Any news here?

**Comment by leyyinad** [comment]
Found one here today. Not sure if it's ready for production but seems to do the job pretty well:

> https://download.nextcloud.com/desktop/releases/Mac/Installer/

**Comment by enoch85** [comment]
Hmm, it's not published on nextcloud.com, how odd.

**Comment by n0lz** [comment]
There is a 2.3.2.1.pkg on the download page now. But still this version don't work with TLS 1.2...

**Comment by silsha** [comment]
Can confirm that. See also #13 and #152.
