### ISSUE TITLE
Sync client non-functional after updating to version 2.3.2

### ISSUE THREAD

**Issue by bertptrs** [nextcloud/client_theming#191]
After updating to version 2.3.2 (from 2.3.1), I get the following error at startup:

> No connection to Nextcloud at https://[REDACTED]. Error transferring https://[REDACTED]/status.php - server replied:

which is caused, I presume, by an empty reply. When I do a `GET` request to the address manually, I get the following proper response:

```json
{
  "installed": true,
  "maintenance": false,
  "needsDbUpgrade": false,
  "version": "12.0.0.29",
  "versionstring": "12.0.0",
  "edition": "",
  "productname": "Nextcloud"
}
```

which seems to show that everything is working.

I removed the URL of my Nextcloud instance from these reports since, well, it doesn't need more attention than it is already getting.

Additionally, before that, it gives me the following error:

> Error while loading the list of folders from the server.
> Error transferring https://[REDACTED]/remote.php/dav/files/bert/ - server replied:

Looking at the server logs, I notice two things:

1. All those requests (aside from the first few, listed below) are getting 503 responses. The first one to fail is a GET request to `remote.php/dav/avatars/bert/128.png`
    1. A GET request to `status.php`
    2. A PROPFIND request to `remote.php/webdav`
    3. A GET request to `ocs/v1.php/cloud/capabilities?format=json`
    4. A GET request to `ocs/v1.php/cloud/user?format=json`
2. The client seems to have moved from HTTP 1.1 (before update) to HTTP 2 (after update). Browsing Nextcloud using Chromium (thus, via HTTP 2) seems to work fine.

**Comment by jebrosen** [comment]
What platform was this on? I was using nextcloud-client from the Arch Linux AUR and it was just fixed today. The package was using the latest git commit to the owncloud client instead of the one nextcloud had pinned, and owncloud's master branch has some issues right now.

**Comment by C0rn3j** [comment]
Had the same issue, after the package update it is gone, I'd close this.

**Comment by bertptrs** [comment]
I can confirm this was with the AUR and that the issues went away with the repackaging, I think this issue can be closed.
