### ISSUE TITLE
2.3.2 release for windows AKA regular builds

### ISSUE THREAD

**Issue by nroach44** [nextcloud/client_theming#195]
There does not appear to be a release of 2.3.2 for windows. As 2.3.1 has a pretty major bug involving uploading (if-match header issue) I've currently got to use an old 2.2 version.

Please build a 2.3.2 release for windows, and ideally have regular release builds.

I do have the hardware and can contribute if need be, but Windows users should not have to build from source. I'm used to it for linux, but I'm not downloading and installing a whole docker image.

**Comment by silsha** [comment]
There seems to be a 2.3.2 release for windows over here: https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.3.2.1-setup.exe

**Comment by nroach44** [comment]
Ok, for some reason I had downloaded this, and I *think* I installed it, but apparently I hadn't. I must have screwed up installing it because I remember thinking that it was a mislabelled beta version or something.

Sorry!
