### ISSUE TITLE
App logo is too big

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/client_theming#20]
The app-logo is quit big and does not really match into the app-drawer and the launchpad on OS X 😁 Could we make it a bit smaller? @jancborchardt 

<img width="280" alt="drawer_1_1" src="https://cloud.githubusercontent.com/assets/19711361/18231188/e974fbda-72b1-11e6-9d59-11d907eb7f26.png">

**Comment by rullzer** [comment]
I think it is the same size. It is just that it is square and not round.

**Comment by LukasReschke** [comment]
Correct. Also adding the icon to the Dock is pretty rare since the app basically works as daemon :)

**Comment by jancborchardt** [comment]
So, closing hence.

**Comment by MariusBluem** [comment]
...the icon is also shown in the launchpad, where more users will see it, but I am fine with that 😁
