### ISSUE TITLE
2.3.2 Appimage does not work with SSL servers on Debian stable and testing

### ISSUE THREAD

**Issue by Yvan-Masson** [nextcloud/client_theming#203]
Hi,

Using the 2.3.2 client Appimage on Debian stable and testing does not work against servers using SSL. 
The main window reports the following error:
`No connection to Nextcloud at https://nextcloud.domain.tld. Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196))`

Running the Appimage with `--logwindow` gives a more promising clue:
`09-13 14:36:57:309 16945 unknown: QSslSocket: cannot call unresolved function SSL_library_init`

Best regards,
Yvan

Edit: I forgot to mention that the 2.3.2 beta Appimage (also available from https://download.nextcloud.com/desktop/) works perfectly.

**Comment by Oliv4945** [comment]
Hi,
I can confirm the error on 2.3.2 while it works with the beta.

I am using Debian Stretch, if it can help

**Comment by symrex** [comment]
Is there currently a possibility to get a .deb for stretch?

**Comment by MagicFab** [comment]
Same here, thanks for the hint regarding the beta version - it worked.

**Comment by mario** [comment]
Working on this.

**Comment by stevemarple** [comment]
Doesn't work for me with Stretch but worked with Jessie. My workaround was to download and install libssl-1.0.0 from https://packages.debian.org/jessie/amd64/libssl1.0.0/download. Set `LD_LIBRARY_PATH` before use:

    LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/openssl-1.0.0::$LD_LIBRARY_PATH"
    ./Nextcloud-2.3.2-x86_64.AppImage

**Comment by ortwinrp** [comment]
I'm running debian 9.2 on two clients and Nextcloud 12.0.3/debian 9.2 on a test server with self-signed ssl certificate.
Nextcloud-2.3.2-x86_64.AppImage and Nextcloud-2.3.3-beta-x86_64.AppImage (2017-10-17)
both throw the same ssl error as reported in the first post. 
Nextcloud-2.3.2-beta-x86_64.glibc2.14.AppImage shows the 'untrusted ssl certificate' dialog on first launch and works fine if the certificate is confirmed. Thats the way it works with my production server with oc 7.something and debian 8.8.

**Comment by marxistvegan** [comment]
Hey all, running debian buster here and I also getting this error both on the 2.3.2 and the beta 2.3.3

**Comment by rullzer** [comment]
So I figured out why. It is because debian does weird naming stuff for their libcrypto libs.

For now install: `libssl1.0-dev`

And it should work

**Comment by CharlesMAtkinson** [comment]
libssl1.0-dev is not available for Debian jessie.  Which libcrypto libs are required?  Would an easier solution be to provide symlinks to the installed libcrypto libs to suit Nextcloud client's needs?

**Comment by rullzer** [comment]
I can't symlink from within the appimage since I don't know what will be available. Anyway please test https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.3.3-x86_64.AppImage as it should work even on debian

**Comment by Yvan-Masson** [comment]
Hi,

I just tested on current Debian testing (Buster) and it works. I do not have a Debian stable (Stretch) to test this release, but I am going to suppose it is also working.

Regards,
Yvan

**Comment by CharlesMAtkinson** [comment]
Tested on Debian Jessie by download, chmod 744 and running.  No defects detected.
