### ISSUE TITLE
[Clarification request] Debian 9 building instructions

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/client_theming#204]
Can someone please check, whether the dependency "libowncloudsync0" (mentioned in https://github.com/nextcloud/client_theming/blob/master/README.md ) is still required ?

In my view, it can(should) be removed in https://github.com/nextcloud/client_theming/blob/master/README.md .

**Comment by m4lvin** [comment]
Yes. I do not have `libowncloudsync0` installed but the client runs fine. I recently setup a [docker built script for Debian 9](https://github.com/m4lvin/nextcloud-client-debian-packaging) based on [this build repo for ubuntu](https://gitlab.com/packaging/nextcloud-client). It only uses [these packages](https://github.com/m4lvin/nextcloud-client-debian-packaging/blob/master/Makefile#L10) and [works fine](https://travis-ci.org/m4lvin/nextcloud-client-debian-packaging/builds) so far.
