### ISSUE TITLE
 When is the nextcloud desktop client 2.3.3 coming out?

### ISSUE THREAD

**Issue by CamZie** [nextcloud/client_theming#214]
Hello,
I would just like to ask, when exactly will the new desktop client (2.3.3) be released? Since some of our customers are experiencing some bugs with the current Nextcloud desktop client version (2.3.2), which will hopefully be fixed in the next version.
Thank you very much in advance.

**Comment by juliusknorr** [comment]
See https://github.com/nextcloud/client_theming/issues/198#issuecomment-336720746

**Comment by jospoortvliet** [comment]
pls test on  https://download.nextcloud.com/desktop/prereleases/

**Comment by m4lvin** [comment]
Can you estimate how long this beta period will be? Or how much / what feedback you want to collect before releasing 2.3.3?

**Comment by jospoortvliet** [comment]
2.3.3 is on the download server, website will have updated in ~30 minutes ;-)

**Comment by jsalatiel** [comment]
will the ppa be updated ? It is still at 2.3.2-20170823.130651~xenial1

**Comment by jospoortvliet** [comment]
@jsalatiel THAT I don't know, it is up to the maintainer of the PPA, we don't create packages for different distributions... Sorry.

**Comment by m4lvin** [comment]
@jsalatiel the person to ask is probably @ivaradi, see also https://help.nextcloud.com/t/linux-packages-status/10216 for other repositories

**Comment by ivaradi** [comment]
The 2.3.3 client is in the PPA since a few hours ago.
