### ISSUE TITLE
PPA and Debian

### ISSUE THREAD

**Issue by ghost** [nextcloud/client_theming#220]
I'm on a fresh install on Debian 9.2, and I had this issue multiple times now, except for that I currently don't know how I fixed it the previous times.

So, on nextcloud.com you will be redirected to the Ubuntu launchpad if you want to install the nextcloud client on Debian. When I tried to run `add-apt-key` I got an error message about `dirmngr` or something similar not installed. So I installed that, but now I get error messages like this:

```terminal
~# add-apt-repository ppa:nextcloud-devs/client
 The Nextcloud desktop client compiled for Ubuntu
 More info: https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp4u1ov2hx/pubring.gpg' created
gpg: /tmp/tmp4u1ov2hx/trustdb.gpg: trustdb created
gpg: key 60EE47FBAD3DD469: public key "Launchpad PPA for Nextcloud development" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'
```

By the way, there are some `S.gpg-agent.*` files. For example in `/run` and in `/root/.gnupg/` after I ran `gpg-agent --daemon`.

I installed Debian 2 or 3 times in the last few months, and it always behaved like that.

**Comment by ghost** [comment]
Related, but all unresolved:

- https://stackoverflow.com/questions/44909408/s-gpg-agent-browser-not-found-error-while-adding-ppa-in-debian-strech
- https://unix.stackexchange.com/questions/375197/s-gpg-agent-browser-not-found-while-adding-ppa-in-debian
- https://unix.stackexchange.com/questions/384337/s-gpg-agent-browser-not-found-in-debian-strech-while-adding-ppa

Edit: Was able to fix it by adding the key by hand:

```terminal
# gpg --keyserver keyserver.ubuntu.com --recv-keys 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469
# gpg --export --armor 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469 | sudo apt-key add -
# apt update
```

However, I see this as a workaround - this does not resolve this issue.

**Comment by ivaradi** [comment]
Unless you insist on installing the client from a PPA, there are clients compiled specifically for Debian 9.0 at the OpenSUSE build service: https://build.opensuse.org/project/show/home:ivaradi and https://build.opensuse.org/project/show/home:ivaradi:beta

**Comment by ghost** [comment]
I didn't know about these. Are those official builds? If so, could they be linked at nextcloud.com?

**Comment by m4lvin** [comment]
There is a link from nextcloud.com to the forum post at https://help.nextcloud.com/t/linux-packages-status/10216 which has an overview of different packages and repositories.

**Comment by ghost** [comment]
So again I am having issues with `nextcloud-client` and Debian 9.3. I am now no longer able to install it at all due to dependency conflicts:

```
root@x:~# apt install nextcloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nextcloud-client : Depends: libnextcloudsync0 (= 2.3.3-20171224.060956~artful1) but it is not going to be installed
                    Depends: libqt5core5a (>= 5.9.0~beta) but 5.7.1+dfsg-3+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I am still confused. At [nextcloud.com](https://nextcloud.com/install/#install-clients) the PPA is clearly advertised to be used for Debian:

> You can find Ubuntu/Debian packages [in this PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client).

Obviously I am doing something wrong here, but what could it be? I just want to use Nextcloud in the official way using the advertised PPA.

-----------

**EDIT**

I didn't even keep on reading after the passage cited above, because it basically said: "For Debian, do this", but a bit later in the text it says:

> See the latest state and more packages [in this post on our forums](https://help.nextcloud.com/t/linux-packages-status/10216).

Following that link, I eventually [came to this](https://m4lvin.github.io/nextcloud-client-debian-packaging/).

Following these instructions after purging everything from the prior install I was able to get it running.

**Conclusion**

- Instructions are unclear/misleading
- Linked packages [here](https://help.nextcloud.com/t/linux-packages-status/10216) look rather unofficial... They work though
- Linked PPA does **not** work and should thus be removed

Thank you all very much for helping me out - I think that **this** issue is resolved. *However*, maybe consider reformulating the download instructions for the client on the official homepage and maybe distributing the packages from official URLs.
