### ISSUE TITLE
do net get it installed on Ubuntu 14.04

### ISSUE THREAD

**Issue by nephilim75** [nextcloud/client_theming#23]
I have ownCloud client installed and try to change the theming to Nextcloud.

Following the [guide](https://github.com/nextcloud/client_theming/) I will fail installing it.

First command `git submodule update --init --recursive` ends up in this:

```
user@SYDEWI-NB01:~$ git submodule update --init --recursive
fatal: Not a git repository (or any parent up to mount point /home/user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The command `cmake -D OEM_THEME_DIR=`pwd`/../nextcloudtheme ../client` creates this reply by system:

```
user@SYDEWI-NB01:~/build-linux$ cmake -D OEM_THEME_DIR=`pwd`/../nextcloudtheme ../client
CMake Error: The source directory "/home/user/client" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

I am completely new working in Linux so I apologise in advance for my questions. How can I get this fixed?

Kind regards
//neph

**Comment by greenorca** [comment]
Hi Neph,

do you have a git directory set up in your HOME-DIR?
If so, enter it, else create it and enter it. Then run 

```
git clone https://github.com/nextcloud/client_theming.git
cd client_theming
git submodule update --init --recursive
```

**Comment by nephilim75** [comment]
This worked so far. Thank you.

I now entered directory /git/client-theming and created the folder "build-linux". I now tried to run command `cmake -D OEM_THEME_DIR=`pwd`/../nextcloudtheme ../client`. This action ends in this message:

```
-- Could not find Qt5, searching for Qt4 instead...
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
-- Found unsuitable Qt version "" from NOTFOUND
Qt QTWEBKIT library not found.
Qt QTGUI library not found.
Qt QTDBUS library not found.
Qt QTXML library not found.
Qt QTSQL library not found.
Qt QTNETWORK library not found.
Qt QTCORE library not found.
-- If possible compile me with Qt 5.4 or higher.
-- Found QtKeychain: /usr/lib/x86_64-linux-gnu/libqtkeychain.so  
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at cmake/modules/QtVersionAbstraction.cmake:139 (qt4_add_resources):
  Unknown CMake command "qt4_add_resources".
Call Stack (most recent call first):
  src/gui/CMakeLists.txt:7 (qt_add_resources)


-- Configuring incomplete, errors occurred!
See also "/git/client_theming/build-linux/CMakeFiles/CMakeOutput.log".
```

 CMake missed a lot of modules. All of them I have installed so far. But this one I have no idea how to solve.

Your assistance is highly appreciated.

Thank you in advance.

**Comment by greenorca** [comment]
Hmm, sorry for the late reply. Do you have these packages installed:

```
#install required libs
sudo apt-get install debhelper cmake sed doxygen unzip libsqlite3-dev python-sphinx libssl-dev libqt5webkit5-dev qt5keychain-dev
```

This solved my troubles on ubuntu1604.

**Comment by nephilim75** [comment]
Thank you. The installation has finished now without any issues but the logo and all the labels didn't change. What did I miss to do?

**Comment by nephilim75** [comment]
Did the installation and it went through just fine but I can not see any change to past. The logo and the lables are just from oC. Any idea what I missed to do?

**Comment by pasbec** [comment]
Did you follow the [build instructions](https://github.com/nextcloud/client_theming/blob/master/README.md) to the very end? As nothing changed, are you really sure to make and install the client after the configuration?

``` bash
make
make install
```

What does

``` bash
which nextcloud
```

say?

**Comment by enoch85** [comment]
Is this issue still valid? Please close otherwise.

JFTR, there is a PPA avaliable now. Read the README for instructions on how to install it.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
