### ISSUE TITLE
Problems compiling for Fedora 24

### ISSUE THREAD

**Issue by stratacast** [nextcloud/client_theming#27]
So I currently got to the cmake part of the process and I am missing dependencies, some of which I have installed. I am missing the KF5 Find (installed all the kf5-kfind files), inotify (also install inotify inotify-devel) and PDFLATEX. Has anyone successfully compiled this on Fedora?

**Comment by ghost** [comment]
Compiled successfully on fedora 24. Could you please provide the output?

**Comment by captbrogers** [comment]
I got mine to compile (I ignored the kf5\* lines as I'm using Gnome 3 not KDE 5) but when I run `nextcloud`, this is what I get:

```
nextcloud: error while loading shared libraries: libnextcloudsync.so.0: cannot open shared object file: No such file or directory
```

But when I run `locate libnextcloudsync`, I see it is installed:

```
/usr/local/lib64/libnextcloudsync.so
/usr/local/lib64/libnextcloudsync.so.0
/usr/local/lib64/libnextcloudsync.so.2.2.4
```

`ls -lh /usr/local/lib64 | grep libnextcloudsync` gives me the following:

```
lrwxrwxrwx. 1 root root   21 Oct 24 15:55 libnextcloudsync.so -> libnextcloudsync.so.0
lrwxrwxrwx. 1 root root   25 Oct 24 15:55 libnextcloudsync.so.0 -> libnextcloudsync.so.2.2.4
-rwxr-xr-x. 1 root root 2.2M Oct 24 20:33 libnextcloudsync.so.2.2.4
```

Any hints as to why I'm getting this error?

**Comment by aldostein** [comment]
Hi, I had to add /ust/local/lib64 to the ld_library_path:

`export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH`

a more permanent solution would be to edit a file in /etc/ld.so.conf.d/<name>.conf:

`sudo echo /usr/local/lib64 > /etc/ld.so.conf.d/local-lib64.conf`

then another problem arose with libssl.so.1.0.0 and libcrypto.so.1.0.0, so I did some symbolic links:

`sudo ln -s /lib64/libssl.so.1.0.2j /usr/local/lib64/libssl.so.1.0.0`
`sudo ln -s /lib64/libcrypto.so.1.0.2j /usr/local/lib64/libcrypto.so.1.0.0`

hope that helps

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
