### ISSUE TITLE
[macOS] Status bar icons do not dim when desktop loses focus

### ISSUE THREAD

**Issue by ViViDboarder** [nextcloud/client_theming#28]
Reproduction steps:
1. Attach two displays
2. Run Nextcloud
3. Look at display that is not active
4. Icon is not dimmed the way all other status bar icons are

**Comment by tsparber** [comment]
Fixed in https://github.com/owncloud/client/pull/5227 (Planned for 2.3.0)

**Comment by ViViDboarder** [comment]
Awesome job! Thanks!

**Comment by LukasReschke** [comment]
Closing as it will be fixed once that is released.
