### ISSUE TITLE
Update Linux Ubuntu mate 16.10

### ISSUE THREAD

**Issue by fampla** [nextcloud/client_theming#31]
I am so sorry but could you tell me how to update the client with Linux?
I know i am new to github so please tell me.

thank you very much

**Comment by pasbec** [comment]
What do you mean with update? Your issue-heading sounds like you'd like to update ubuntu...

You should probably provide a bit more details about what you have done and what you would like to achive exactly.

**Comment by hanzei** [comment]
The is a ppa now. Does it work and update with this?

**Comment by enoch85** [comment]
@Slevin7 

`apt update`
`apt upgrade`
