### ISSUE TITLE
fatal error: QWebView missing when try to compile client

### ISSUE THREAD

**Issue by Jugulaire** [nextcloud/client_theming#35]
Hi, 

When i try to compile the client, i got a error on make. 
Make say i have a missing lib 
`fatal error: QWebView`

I have check with apt-file to install it but when it's done the error come again. 
Anybody have the same issue ?

**Comment by VGoshev** [comment]
Which package have you installed? For building you need -dev version of package

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
