### ISSUE TITLE
NextCloud 2.2.4 (b1) is not connecting to the same server as ownCloud 2.2.4 does

### ISSUE THREAD

**Issue by childnode** [nextcloud/client_theming#39]
```
OCC::DiscoveryJob(0x7ff84060f8c0)  Calling into main thread...
!!! OCC::LsColJob created for "https://traut.cloud/" + "" "OCC::DiscoverySingleDirectoryJob"
SslHandshakeFailedError:  "SSL handshake failed"  : can be caused by a webserver wanting SSL client certificates
void OCC::AbstractNetworkJob::slotFinished() 6 "SSL handshake failed" QVariant(Invalid)
void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply *) "SSL handshake failed" 0 6
void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, const QString &) 5 "SSL handshake failed"
OCC::DiscoveryJob(0x7ff84060f8c0)  ...Returned from main thread
5 when opening  msg= "SSL handshake failed"
[10/24 23:22:23.286556, 4] csync_ftw:  opendir failed for ownclouds://traut.cloud/remote.php/webdav - errno 5
[10/24 23:22:23.286678, 6] csync_statedb_close:  sqlite3_close=0
 #### ERROR during  csync_update :  "An error occurred while opening a folder SSL handshake failed"
```

for SSL details please see
https://www.ssllabs.com/ssltest/analyze.html?d=traut.cloud&s=87.230.17.213 

Perhaps a OpenSSL 1.0.2h->j issue?! 
Only affected: Mac version. Windows version is working fine. Linux not tested.

Unfortunatly I can't see any further logs ...

Difference you can see as a user:
![bildschirmfoto 2016-10-24 um 23 26 36](https://cloud.githubusercontent.com/assets/192814/19673266/77a60914-9a7e-11e6-9702-611a6fa77322.png)

P.S: Mac OSX 10.11.6

perhaps anyway related to some users do have problems with ownCloud itself?
https://github.com/owncloud/client/issues/5217

![bildschirmfoto 2016-10-24 um 23 04 33](https://cloud.githubusercontent.com/assets/192814/19721048/ef87d302-9b70-11e6-9f0a-a759d759d5ec.png)

**Comment by childnode** [comment]
perhaps anyway related to some users do have problems with ownCloud itself?
https://github.com/owncloud/client/issues/5217

**Comment by jospoortvliet** [comment]
So this is a known issue, and it is a problem in Qt. The Qt shipped with the ownCloud Client has some custom patches in it but it is quite a complicated and prone-to-break process to ship with a patched Qt so we don't. A future version of the client will work with Qt 5.6, though, which should fix this problem. Sorry, there isn't really anything we can do now other than contribute to making the client work with Qt 5.6! Which we do but that will take time.

**Comment by childnode** [comment]
oooo...kay .... then ... still using the patched ownCloud, perhaps you should make this (temporary) drawback / known issue more public?!
Perhaps you also have some details about the "known issue"? Some "known Workarounds"? (enabling old ciphers, etc?!)

**Comment by rullzer** [comment]
Basically a dup of https://github.com/nextcloud/client_theming/issues/13
