### ISSUE TITLE
Share from Windows Desktop app not working

### ISSUE THREAD

**Issue by pfloor** [nextcloud/client_theming#41]
### Expected behaviour

Right click any file or folder should bring up "Share with Nextcloud"
### Actual behaviour

There are no icons on any files or folders and there is no option to "Share with Nextcloud" from within file explorer when I right click a file or folder.
### Steps to reproduce
1. Shut down Owncloud and Install latest Nextcloud client Version 2.2.4 (build 2)
2. Shut down Nextcloud client, copy config file from Owncloud client. and uninstall Owncloud client.
3. Reboot.
### Server configuration

Operating system: SME Server 9 (Centos 6.7 derivative)

Web server: Apache 2.2.15

Database: MySQL 5.1.73

PHP version: 5.6.24-1

ownCloud version: 10.0.1

Storage backend (external storage): N/A
### Client configuration

Client version: 2.2.4 (build 2)

Operating system: Windows 10

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud
### Logs
1. Client logfile: 
   https://gist.github.com/pfloor/fa0d45cc581283e580305a2b235540ac
2. Web server error log:
   `[Thu Oct 27 00:22:12 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
   [Thu Oct 27 00:22:17 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
   [Thu Oct 27 01:05:59 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
   [Thu Oct 27 01:06:03 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
   [Fri Oct 28 10:44:00 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
   [Fri Oct 28 10:55:53 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt`
3. Server logfile: ownCloud log (data/owncloud.log):
   https://gist.github.com/pfloor/a6334b7a0764698f1b734447bf9cf7d7

**Comment by pfloor** [comment]
UPDATE:
This appears to be a problem with the re-branding, more specifically the location of the program files.

The problem only exists when I uninstall the owncloud client (or move or rename the Owncloud program files directory) so it seems that Nextcloud may be using resources located in the Owncloud program files directory.  If I re-install Owncloud but not start it and only start Nextcloud then the icons and the sharing option return.

**Comment by rullzer** [comment]
this is more of an issue with windows and the limited explorer icons. Most likely it would also have worked if you just reinstalled the nextcloud program (after uninstallting the oC one).

**Comment by pfloor** [comment]
Uninstalling OwnCloud and reinstalling Nextcloud worked.

I guess the issue stems from the instructions here that I followed...

https://help.nextcloud.com/t/copy-the-owncloud-sync-client-configuration-when-switching-to-the-nextcloud-client/2537

These instructions make no mention of reinstalling NC after uninstalling OC.

**Comment by ftiede** [comment]
I've stumbled across something similar, I have the same problem with the dolphin (KDE) integration - the context menu just doesn't appear.

Investigating the sources (with external submodules) revealed that the binaries created by Nextcloud-themed compiling are named "nextcloud"<subbinaryname> instead of "owncloud"<subbinaryname>.
At least the KF5 service file doesn't have this flexibility and thus still references a now no longer existing binary with the observed missing of the context menu.

Way I see it, there are two options: Open a pull-request with owncloud/oc-client and hope they'll integrate added (yet from their point-of-view unnecessary) flexibility to the desktop integration control files or try and patch the submodule from the nextcloud-theme CMake files.

Maybe I'll try to figure something out for the latter option the next couple of days/weeks.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by pfloor** [comment]
This issue seems to have resolved itself.  Sorry, didn't know that I was supposed to close this.  Closing now.

Thanks!
