### ISSUE TITLE
18 hours after setting up NextCloud Windows Desktop Client, no files downloaded

### ISSUE THREAD

**Issue by dolevu** [nextcloud/client_theming#45]
**Expected behaviour**

All files should be downloaded within 2 hours like Dropbox or Google Drive

**Actual behaviour**

I've let the client running for over 18 hours, and it still "checking for changes in..." many subfolders, and no files downloaded.

If I uncheck some folders that have many subfolders and small files, it start downloading other folders after 15 minutes.

**Server configuration**

Operating system: Ubuntu 16.04

Web server: Nginx 

Database: Maria DB

PHP version: 7

NextCloud version: 10.0.1

Storage backend (external storage): N/A

**Client configuration**

Client version: 2.2.4 (build 2)

Operating system: Windows 10

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud

**Log**

"11-13 12:16:35:885 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:36:291 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 2 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app"
11-13 12:16:36:291 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app ...Returned from main thread
11-13 12:16:36:291 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src Calling into main thread...
11-13 12:16:36:306 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:36:697 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src"
11-13 12:16:36:697 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src ...Returned from main thread
11-13 12:16:36:697 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main Calling into main thread...
11-13 12:16:36:713 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:37:072 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 3 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main"
11-13 12:16:37:088 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main ...Returned from main thread
11-13 12:16:37:088 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java Calling into main thread...
11-13 12:16:37:088 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:37:447 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java"
11-13 12:16:37:463 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java ...Returned from main thread
11-13 12:16:37:463 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com Calling into main thread...
11-13 12:16:37:463 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:37:822 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com"
11-13 12:16:37:822 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com ...Returned from main thread
11-13 12:16:37:822 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware Calling into main thread...
11-13 12:16:37:838 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:38:197 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware"
11-13 12:16:38:197 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware ...Returned from main thread
11-13 12:16:38:197 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android Calling into main thread...
11-13 12:16:38:213 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:38:572 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android"
11-13 12:16:38:572 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android ...Returned from main thread
11-13 12:16:38:572 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android/actionbaroverlay Calling into main thread...
11-13 12:16:38:588 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android/actionbaroverlay" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:38:947 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android/actionbaroverlay"
11-13 12:16:38:947 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android/actionbaroverlay ...Returned from main thread
11-13 12:16:38:963 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android/actionbaroverlay"
11-13 12:16:38:963 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware/android"
11-13 12:16:38:963 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com/commonsware"
11-13 12:16:38:963 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java/com"
11-13 12:16:38:963 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/java"
11-13 12:16:38:963 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res Calling into main thread...
11-13 12:16:38:978 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:39:182 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://xxx.xxx" + "/" "OCC::QuotaInfo"
11-13 12:16:39:338 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 8 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res"
11-13 12:16:39:338 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res ...Returned from main thread
11-13 12:16:39:338 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable Calling into main thread...
11-13 12:16:39:353 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:39:708 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable"
11-13 12:16:39:708 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable ...Returned from main thread
11-13 12:16:39:708 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable"
11-13 12:16:39:708 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-hdpi Calling into main thread...
11-13 12:16:39:724 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-hdpi" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:40:099 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 4 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-hdpi"
11-13 12:16:40:099 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-hdpi ...Returned from main thread
11-13 12:16:40:099 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-hdpi"
11-13 12:16:40:099 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-ldpi Calling into main thread...
11-13 12:16:40:115 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-ldpi" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:40:490 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 1 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-ldpi"
11-13 12:16:40:490 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-ldpi ...Returned from main thread
11-13 12:16:40:490 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-ldpi"
11-13 12:16:40:490 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-mdpi Calling into main thread...
11-13 12:16:40:505 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-mdpi" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:40:865 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 4 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-mdpi"
11-13 12:16:40:865 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-mdpi ...Returned from main thread
11-13 12:16:40:880 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-mdpi"
11-13 12:16:40:880 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xhdpi Calling into main thread...
11-13 12:16:40:880 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xhdpi" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:41:255 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 4 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xhdpi"
11-13 12:16:41:255 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xhdpi ...Returned from main thread
11-13 12:16:41:255 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xhdpi"
11-13 12:16:41:255 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xxhdpi Calling into main thread...
11-13 12:16:41:271 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xxhdpi" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:41:724 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList&) Have 3 results for "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xxhdpi"
11-13 12:16:41:724 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xxhdpi ...Returned from main thread
11-13 12:16:41:724 0x5db69f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x78ffb80) "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/drawable-xxhdpi"
11-13 12:16:41:724 0x5db69f0 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x78ffb80) Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/menu Calling into main thread...
11-13 12:16:41:724 0x4347ac8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://xxx.xxx" + "/Doc/Android/The Busy Coder's Guide to Android Development Version 7.4/ActionBar/OverlayNative/app/src/main/res/menu" "OCC::DiscoverySingleDirectoryJob"
11-13 12:16:42:099 0x4347ac8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void

**Comment by pixolin** [comment]
Guess, I have a similar situation here:
I want to share settings and addons for the Atom Editor which I use on two Macs (laptop and desktop). Unfortunately the Atom folder consists of thousands tiny files and my desktop clients keep searching for changes in all files, before it starts synchronizing. 

I found out, that part of the problem were my energy saving settings. It seems, the desktop client starts all over checking for changed files, after the computer went into sleep mode. When I _disabled_ the energy setting _automatically set all programs to sleep mode_, at least the check for changed files could be completed and the files synched afterwards. Synchronization of about 300 MB still took about two days though.

I also synched a couple of larger zip-files. That worked pretty fast (within minutes) as only a small amount of files needed to be checked for changes.

I'm using the _Mac_ Nextcloud Desktop client (version 2.2.4, build 1) on both computers and run Nextcloud Server 10.0.1 on the new Nextcloud Box (yay!) (operating system Ubuntu Snap). Please let me know, if you need further details.

PS: Out of curiosity I just installed [CrossCloud](https://crosscloud.me/) desktop client. After providing URL and credentials, it checks a couple of files for changes, but then immediately starts to synchronize - the behavior I actually would expect\* from Nextcloud's Desktop client. 
(*not complaining here, just trying to explain the desired result)

**Comment by dolevu** [comment]
@pixolin in my case, it's the new clean setup.
Shouldn't it just download the folders and files on server to the local folder, while the local is empty, and it's newly set up? I don't understand why it needs to check for changes at the first run.

I still can't download 3 folders that have a lot of subfolders, and small files, the total size is around 1.5GB

**Comment by pixolin** [comment]
Well, I guess as long as the sole purpose of this repo is, to fork https://github.com/owncloud/client.git, we won't get any answers to our issues here.

**Comment by jancborchardt** [comment]
cc @rullzer any clue here?

@pixolin it’s not a fork, only a theme for now. So this issue will most likely be the same with the original client. We think it’s not a good idea to split development in that respect, especially because activity in the original repository is very low since recent events. :\

**Comment by dragotin** [comment]
@jancborchardt stop your FUDding. Six merges of HUGE code is _very low_ ? What are you talking about?

**Comment by jancborchardt** [comment]
@dragotin sorry, it was meant as an explanation why there was no desktop fork, not as discredit. I just looked at the graphs https://github.com/owncloud/client/graphs/contributors and activity is considerably lower since summer, especially from you. :\ I don’t spread FUD.

**Comment by pixolin** [comment]
Um, well … I actually didn't want to start arguing who is working on what repository. 😄 
My latest remark was actually meant to question, if this issue is posted in the right repo. The important part of @jancborchardt 's response was for me

> So this issue will most likely be the same with the original client.

… and in fact I have tried out the desktop client provided by Owncloud to experience the same issue. My intention was to ask, whether we should in that case close the issue here and open another thread in Owncloud's repo.

I know, you all do a great job. Thank you for that. ❤️

**Comment by jturcotte** [comment]
@pixolin If you can confirm that this also happens with the ownCloud server, your bug report will be welcome at https://github.com/owncloud/client

Also have a look at https://github.com/owncloud/client/issues/5095 before you do, just in case you have the same issue.

**Comment by pixolin** [comment]
@jturcotte Cheers, I was already looking for duplicate issues. Will add my bug report soon.

**Comment by jancborchardt** [comment]
@jturcotte thanks for linking the issue! :)

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!

**Comment by dolevu** [comment]
So I just tried the latest Nextcloud server, latest Nextcloud client, the same issues.

You guys can test it easily, just install Nextcloud server, upload a 10GB folder that has all MP3 files.
Then install Nextcloud client, both MAC and Windows version have the same issue, it takes forever to start syncing.
