### ISSUE TITLE
Linux client fails to reconnect after suspend

### ISSUE THREAD

**Issue by drwahl** [nextcloud/client_theming#47]
On Ubuntu 14.04 and Ubuntu 16.04, the client fails to ever reconnect after the computer has woken up from suspend.  Even after opening the (already running) client and trying to forcibly reconnect, it refuses to connect.  The only way I've found to get it to connect again is to close the client fully and restart it.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by drwahl** [comment]
I have not had issues with the nextcloud client.  I honestly don't know what fixed it, but props to whoever made my life easier! Thanks!
