### ISSUE TITLE
error while loading shared libraries: libnextcloudsync.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by gisforgirard** [nextcloud/client_theming#48]
compiled the nextcloud client, did make && make install

trying to run nextcloud i get the error in the title

i ran strace on nextcloud to see where it's looking for the file:

open("/usr/local/lib/x86_64-linux-gnu/nextcloud/libnextcloudsync.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

i ran locate to find if the file was installed, the following files come up:

/usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so
/usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so.0
/usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so.2.2.4
/usr/local/lib/x86_64-linux-gnu/nextcloud
/usr/local/lib/x86_64-linux-gnu/nextcloud/libocsync.so
/usr/local/lib/x86_64-linux-gnu/nextcloud/libocsync.so.0
/usr/local/lib/x86_64-linux-gnu/nextcloud/libocsync.so.2.2.4

ran:
cp /usr/local/lib/x86_64-linux-gnu/libnextcloudsync.so* /usr/local/lib/x86_64-linux-gnu/nextcloud/

problem solved, just wanted to let you know
system: ubuntu 16.04

**Comment by this-tech** [comment]
for Fedora 25 the fix was

ln -s /usr/local/lib64/libnextcloudsync.so.0 /usr/lib64/libnextcloudsync.so.0

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by gisforgirard** [comment]
i have no idea why i posted this in theming. my bad.
