### ISSUE TITLE
parameter to prevent saving credentials in in keyring/windows credentials vault

### ISSUE THREAD

**Issue by chaos-prevails** [nextcloud/client_theming#51]
Dear nextcloud community

we are a small non-for-profit organization. Due to our limited budget, when colleagues work from home, they use their private laptops. I know not perfect, but that's how it is ....

We would like to not leave any credentials/passwords on the private laptops when using the sync client. We would sync to a USB-stick and keep the configuration directory there (confdir parameter). Yet, the sync client automatically saves the credentials in the windows credentials vault.

Are there any plans to disable this behaviour via a parameter? Or is there a hidden parameter? Ideally nothing is saved on the client computer. Servername and username are in the confdir, so users would only need to type their password.

Of course I can delete the credentials with the cmdkey (and use similar cmds for mac and linux I guess), but it would be great to prevent it in the first place ...

It seems I could compile the qtkeychain and use the DUSE_CREDENTIAL_STORE=OFF but that's only Windows.

Tim

**Comment by VGoshev** [comment]
I can't answer for developers, but looks like for your case, using WebDAV for accessing files in Nextcloud suits much better.

**Comment by chaos-prevails** [comment]
with webdav the credentials are saved in the Credentials Vault as well, so no solution unfortunately.

**Comment by VGoshev** [comment]
But there are lots of different apps for webdav in Linux (you are using Linux, I'm right?). For example, you can use fuse-based davfs2, which, as far as I know, doesn't store password anywhere and available as package in most of popular Linux Distributives

**Comment by chaos-prevails** [comment]
hello,

My colleagues mostly have Windows computers at home. I like the nextcloud interface where you can share directly in the file explorer (I think that this is a unique owncloud/nextcloud client feature?). But it is indeed a good idea to look into other programs and check their compatibility and where they save credentials and other configuration. Thanks!

**Comment by rullzer** [comment]
It sounds to me you would be better of enabling 2 factor authentication and creating specific app passwords for each laptop. That way you could still revoke access if their machine gets lots/stolen/whatever.

Not storing the credentials is not as easy as it sounds since we read the credentials always from the store so then we would need to cache the password somewhere etc.

Also how do you prevent their browsers from storing the password when they login via the web?

**Comment by chaos-prevails** [comment]
Dear Rullzer,

thank you for your comments.

AFAIK 2 factor authentication is not (yet) available for the (windows) NC client. or is it? Otherwise this would be a good idea solving my problem.

Ad browser password and NC website: we use firefoxportable in the veracrypt container, so the login credentials are not stored in their private-pc browser's cache.

What I am currently testing (and was planning to roll out) is:
- install the nextcloud client + the NC confdir + the sync folder in a veracrypt container on a usb stick. As soon as colleagues stop working on their private pc, all data is in the veracrypt container on the USB stick (except the password)
- a script which deletes the credentials from the vault after logging in with the NC client. Syncing works even after I have deleted the credentials from the vault (I tested only for a couple of minutes after deleting the password from the vault).

If the NC client has to reread the credentials from the vault after the initial login, I have to think of something else. I could have a script which needs to run after colleagues finish working, but that seems not reliable to me (might happen more often than not that colleagues forget to run the last script).

thanks,
tim

**Comment by rullzer** [comment]
Well, lets put it this way. After the first login a session should be started and that should be used. However if for some reason this session gets killed the user has to relogin.

2FA is not available in the client itself. But you can enable it. The workflow then becomes:

1. Login via web using 2FA
2. Go to personal settings
3. Create an app password
4. Login in the desktop app using your username + the apppassword

Now this apppassword will still be stored in the vault. But at least now you have control over who has access. And you can revoke access easily.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
