### ISSUE TITLE
building nextcloud client for macOS 10.12.1 - qt single error 404

### ISSUE THREAD

**Issue by novski** [nextcloud/client_theming#52]
I tried to follow the guide for Mac but this does not exist:
$ wget http://download.qt.io/official_releases/qt/5.4/5.4.0/single/qt-everywhere-opensource-src-5.4.0.tar.gz
--2016-12-22 10:31:05--  http://download.qt.io/official_releases/qt/5.4/5.4.0/single/qt-everywhere-opensource-src-5.4.0.tar.gz
Resolving download.qt.io... 77.86.229.90
Connecting to download.qt.io|77.86.229.90|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-22 10:31:05 ERROR 404: Not Found.

not sure if I can go with $ wget http://download.qt.io/official_releases/qt/5.7/5.7.1/single/qt-everywhere-opensource-src-5.7.1.tar.gz

you can see here there is no 5.4 available anymore: http://download.qt.io/official_releases/qt/

I tried it but then the config does not work:

instead of this:
./configure -sdk macosx10.9

I tried it like this:
./configure -sdk macos10.12.1

and get this:
Failed to resolve SDK path for 'macos10.12.1

I can't solve it...

**Comment by JaredBoone** [comment]
This link works: http://download.qt.io/archive/qt/5.4/5.4.0/single/qt-everywhere-opensource-src-5.4.0.tar.gz

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
