### ISSUE TITLE
Cosing the connection wizard does not close the app

### ISSUE THREAD

**Issue by caco3** [nextcloud/client_theming#53]
When you have a new installation (or no nextcloud.cfg), the client (2.2.4) will show a connection wizard.
When you close this client (top right x), the window gets closed, but the client continues running (there is still an icon in the systray).

I would suggest that in such case the app gets closed.
Else point 4 in https://help.nextcloud.com/t/how-to-migrate-your-owncloud-desktop-client-to-nextcloud/6808 will not work as expected!

Tested with the Nextcloud client 2.2.4 from http://repo.morph027.de/#nextcloud-client using Kbuntu

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by caco3** [comment]
Just tested: It still is the same issue with version 2.3.1
The issue is still open because it seems that nobody picked it up.
It is not a theming issue, but there seems to be no other repo for the client!

**Comment by enoch85** [comment]
@caco3 Yes, there is; ownCloud. As you can see when you opened the issue all issue that **not** are related to the theming should be reported in the upstream repo.

> Is this issue related to the ownCloud client, (thus not an theming isssue) please close it and report the issue here instead.

**Comment by enoch85** [comment]
Maybe @juliushaertl can help out here (creating a PR in the ownCloud repo)?

**Comment by caco3** [comment]
Well, it is not too obvious that people who are using the NEXTCLOUD client have to file bugs against the OWNCLOUD client!

**Comment by enoch85** [comment]
@caco3 That's why this repo is called `client_theming` and not `client`. It seems you posted your issue before we made that clear in the [issue_template.md](https://raw.githubusercontent.com/nextcloud/client_theming/master/issue_template.md)

Sorry for the confusion.

**Comment by caco3** [comment]
Good point!
I created a new issue @ https://github.com/owncloud/client/issues/5817

Why don't you add this note into README.md? Most people will not look for issue_template.md.

**Comment by enoch85** [comment]
When you create a new issue you are presented with `issue_template.md`. The `README` is for other stuff.

Thanks for creating the new issue!
