### ISSUE TITLE
Nautilus integration not working with Nextcloud 11 and application passwords. Syncing works fine.

### ISSUE THREAD

**Issue by elpraga** [nextcloud/client_theming#55]
Plese, let me know if this is the correct place to report the issue. 

I would really like to make the integration with nautilus work again. It was very handy..

**Comment by enoch85** [comment]
Ref https://github.com/nextcloud/client_theming/pull/65/commits/e34f4a21b904d5dd5e3c8df03e58dd6e1c3a801b

**Comment by enoch85** [comment]
Please close this issue if that commit fixed it.

**Comment by elpraga** [comment]
@enoch85 , I am sorry for such a late response. I couldn't try to compile before.

The file `syncstate.py` is included now, but  overlay icons don't work yet, there is another problem.

In short.. The default install path after compiling nextcloud client is `/usr/local/` `syncstate.py` is created in `/usr/local/share/nautilus-python/extensions/`. When launching nautilus, the `socket` is created correctly, but following message appears:

```
Connect could not be established, try again later!
Connect could not be established, try again later!
Connect could not be established, try again later!
Connect could not be established, try again later!
```

After some fiddling around, I did the following:

`mv /usr/local/share/nautilus-python/extensions/syncstate.py /usr/share/nautilus-python/extensions/syncstate-nextcloud.py` 

I chose to change the name to be able to install both `owncloud` and `nextcloud` clients at the same time.

I still get sometimes `Connect could not be established, try again later!` messages, but overlay icons appear correctly (OK messages appear now as well)

* Do you have any idea why the icons do not appear if the same file is installed in `/usr/local`?
* Would it be possible to officially rename `syncstate.py` to `syncstate-nextcloud.py` to avoid possible problems when both clients are installed simulteneously?

Thank you for your help!

**Comment by enoch85** [comment]
cc @ivaradi

**Comment by elpraga** [comment]
@enoch85 I'm sorry if I didn't manage to explain myself clearly. I'll try one more time.

After a standard installation overlay icons __don't work__.

That is why I didn't close the issue.

I'll gladly provide as much information as I can.

Tomas

**Comment by enoch85** [comment]
Yes, I understood. The issue is still open, right. ;)

Though, this is not my area of expertise, that's why I cc'ed @ivaradi. :)

**Comment by elpraga** [comment]
Thank you! :+1:

I tried, but I didn't understand why it would behave like that.

**Comment by ivaradi** [comment]
- The icons probably don't appear when installed under ``/usr/local`` because Nautilus does not look for plugins there, as it was compiled with a prefix ``/usr``. I think the corrext fix for this situation is to compile and install everything with the same prefix. Or perhaps the upstream client's make system could be modified to allow the user to specify a variable with the prefix for the file manager.
- The name of the plugin file is indeed changed as you suggest in recent Ubuntu packages by patching the sources. This seems to have been fixed in the upstream client on branch 2.3.0-beta1.

**Comment by elpraga** [comment]
Glad to hear about the plugin name change!

But the issue with the installation in `/use/local` is different. Nautilus does recognize the plugin, and loads it, but it doesn't work.

I couldn't compile it with `/usr` prefix as some of the files would conflict.

Is the name change going to be applied here as well? I compiled yesterday using git, but the name of the plugin was the same..

**Comment by ivaradi** [comment]
The name change is present on the `2.3.0-beta1` branch, but that branch uses the `2.3.0-beta1` version of the original client (which is used as a submodule here only).

The issue with `/usr/local` looks strange. If I move my plugin there, Nautilus does not find it at all (I am using Ubuntu 16.10). Could you extend the code printing the error message with printing the exception? E.g. adding a line after the `print` statement printing the message:

`print("Connect could not be established, try again later.")`
`print(str(e))`

**Comment by elpraga** [comment]
Ok, @ivaradi . I found the cause of the message. And it is embarrassing. I found that I had `~/.local/share/nautilus-python/extensions/syncstate.py` sitting there causing the messages. 

Now, I can confirm what you wrote before.  The extension does not work when installed in `/usr/local`

I am sorry to confuse you. 

So are you saying that with the version `2.3.0` both ownCloud and Nextcloud clients can be installed alongside with the `/usr` prefix?

Do you have any idea when it will be released?

And since `/usr/local/` is the defaul prefix when compiling nextcloud client, but overlay icons do not work when installed in this location, should `/usr` be the default prefix? Or should at least a warning be written in the README to warn about this issue? What do you think?

**Comment by elpraga** [comment]
And one more (unrelated) issue about the `README.md` file. It actually does not say how to get the source. I recognize that I am not experienced, but it took me about an hour of trying different things before I got to running `git clone --recursive https://github.com/nextcloud/client_theming nextcloud-client` --- which I hope is the correct way of getting the source the first time.

Could it be added to the `README.md` file for the not so git guru people like me? Especially since _Nextcloud_ officially does not provide binary packages and has the source listed as the official way to obtain the linux client. Or should I open an new issue for that?

**Comment by elpraga** [comment]
And what would be the correct way of changing the prefix? I am not familiar with `cmake` and not even running `cmake --help` gave me the answer. 

I am sorry to ask questions that may seem to trivial to you, but they might not be for some other people. I do not code for living.. :angel: :smiley:

**Comment by ivaradi** [comment]
`/usr/local/` is usually the default prefix in most open-source packages. It assumes that you have some packages installed from your distribution, which go under `/usr`, and you have some other packages that you compile and install yourself and these go under `/usr/local`. So I think the default is fine. At least apart from not working for the case when you have Nautilus from your distribution, but want to compile the Nextcloud client yourself :)

To make the prefix `/usr`, you need to specify it as a variable setting for cmake:

`cmake -DCMAKE_INSTALL_PREFIX=/usr`

(That said I am not that familiar with cmake myself, the Ubuntu package build system provides some kind of a library that one can use, and that library sets this variable.)

BTW, what distribution do you use? Could you not use the Ubuntu or Debian packages instead of compiling the application for yourself?

**Comment by elpraga** [comment]
Thank you so much for the prefix tip! It saved me a lot of time! :smiley:

You're right about the `/use/local` prefix, it is better for things you compile yourself,  but I do think that there should be some kind of warning if something is broken because of the location (more so if it's as easy to fix afterwards as to copy one file)

I use _Ubuntu 14.04_ on my desktop.  And I do have the ownCloud client, but since I'm using NextCloud now, I wanted to finish rebranding. (And also because my wife was asking why does it say "Share with ownCloud" when we're using NextCloud now :smiley:)

Thank you so much for your help!

**Comment by ivaradi** [comment]
You're welcome! But if you are using Ubuntu 14.04, you could download the client from the PPA (see the latest version of the README file for instructions). Trusty (14.04) is supported.

**Comment by elpraga** [comment]
Wow! Than you for pointing it out! It wasn't there when I started to compile it!

Thank you!

**Comment by elpraga** [comment]
With the release of the PPA, I think I can close this issue, as now overlay icons will work out of the box for most of the users. 

I still think though that a small warning about the icons not working when installing the client to `/usr/local/` would be helpful.

Thank you for your help!
