### ISSUE TITLE
Icon name in desktop launcher is wrong

### ISSUE THREAD

**Issue by resoli** [nextcloud/client_theming#57]
nextcloud.desktop file expects icon file name (before extension) equal to @APPLICATION_EXECUTABLE@ , but it is not (it starts with capital letter, "Nextcloud").

This results in generated nextcloud.desktop showing no icon.

**Comment by Fjodor42** [comment]
Have a look at https://github.com/nextcloud/client_theming/commit/99841e9a4030a24d8487bdbae48bf69e8206e613

**Comment by alexanderdd** [comment]
That sounds like an easy fix?! (I have no clue about coding..)

**Comment by Fjodor42** [comment]
Possibly not, afterall.

I tried som renaming and stuff - please see my preliminary analysis just now at https://github.com/linuxmint/Cinnamon/issues/6143

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by alexanderdd** [comment]
I don't know if "icon name in decktop launcher" is the problem, but I am not seing a nextcloud icon in my notification area on Linuxmint 18.1 Cinnamon with nextcloud client 2.3.1 (even if I insert a startup delay of 9 seconds).

As @enoch85 mentioned, this might be the wrong place to report this, can somebody else report it in the right place if applicable? I don't want to do it.

**Comment by enoch85** [comment]
When actually reading the post in this issue it seems that this is fixed with the commit by @rullzer 

Please reopen if not.

**Comment by Fjodor42** [comment]
@enoch85 Sorry, no, please reopen.

The commit referenced above seems to be the one that *broke* it - at least for me, as a Cinnamon-on Ubuntu Linux user.

**Comment by Fjodor42** [comment]
Well, trying from source, current HEAD versus HEAD + git revert 99841e9a4030a24d8487bdbae48bf69e8206e613 seems not to do any difference.

Hence, could be packaging or could be Cinnamon - will take it to Cinnamon devs.

**Comment by resoli** [comment]
As stated when opening the bug, in  `client/mirall.desktop.in ` Icon=@APPLICATION_EXECUTABLE@ and application executable is lowercase. So https://github.com/nextcloud/client_theming/commit/99841e9a4030a24d8487bdbae48bf69e8206e613 broke things. In my view the simpler option is  to set an @APPLICATION_ICON@ variable in all `Icon=` instances and externally set  APPLICATION_ICON to 'Nextcloud'.

**Comment by enoch85** [comment]
> In my view the simpler option is to set an @APPLICATION_ICON@ variable in all Icon= instances and externally set APPLICATION_ICON to 'Nextcloud'.

cc @juliushaertl @rullzer Your area of expertise --^

**Comment by resoli** [comment]
Just seen that this was already done in `linux/debian/nextcloud-client/debian/patches/fix-application-icon-name.patch`; the variable used is @APPLICATION_SHORTNAME@ .
