### ISSUE TITLE
Same variables of OC desktop client

### ISSUE THREAD

**Issue by daorte** [nextcloud/client_theming#6]
The 2.2.3-rc1 still uses configuration variables of OC desktop client.

i don't know the name of all configuration variables used on the entire project, but these are the ones i'm using:

**Environment variables**:
- `OWNCLOUD_CHUNK_SIZE`
- `OWNCLOUD_MAX_PARALLEL`

**Windows Registry keys**:
- 32 bits Windows `HKEY_LOCAL_MACHINE\Software\ownCloud\ownCloud`
- 64 bits Windows `HKEY_LOCAL_MACHINE\Software\Wow6432Node\ownCloud\ownCloud`

The key is `skipUpdateCheck`

btw, i had to set OWNCLOUD_MAX_PARALLEL to 1 (The use of this variable is no documented) to upload files sequencially, because uploading multiple files in parallel i can exceed the user quota easily.

**Comment by LukasReschke** [comment]
Those are hard-coded in the source code. This would require a change to the client to make this themable.

**Comment by rullzer** [comment]
Yes this is just theming. For now we don't want to fork the client yet.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.
