### ISSUE TITLE
Build and link AppImage for stable release

### ISSUE THREAD

**Issue by probonopd** [nextcloud/client_theming#61]
Right now an [AppImage](http://appimage.org/) for Linux is produced for each commit on Travis CI and can be downloaded from a temporary transfer.sh URL that is visible toward the end of each [Travis CI build log](https://travis-ci.org/nextcloud/client_theming/). Few people will ever find it there.

Hence, build an AppImage for the stable release and link it on the [download page](https://nextcloud.com/install/#install-clients) instead of "Source":

![](https://lh3.googleusercontent.com/H0Cf0F-5FJZ21IHbGZMfnxx6iarglCfFlStZjQ-yNqmkyGpqiqV9YfE18MN48pzrr3J3CBTO3DWQbA=w717-h544-no)

**Comment by rullzer** [comment]
@jospoortvliet please have a look

**Comment by probonopd** [comment]
ping @jospoortvliet, in https://help.nextcloud.com/t/linux-distribution-packages-for-the-desktop-clients-help-out/2538/75 the question was asked where to download the AppImage.

**Comment by shadeslayer** [comment]
+1 to this please.

**Comment by rugk** [comment]
Any news?

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by probonopd** [comment]
Looks like it's coming, thanks to @rullzer:
https://rullzer.com/nextcloud-desktop-client-appimage.html
