### ISSUE TITLE
Backup Detected message - Client stops working until selection

### ISSUE THREAD

**Issue by stanelie** [nextcloud/client_theming#63]
Hello.

I am experiencing the same issue as https://github.com/owncloud/client/issues/5260 . I get a popup message from the client saying that a "backup was restored" on the server, and I have to click on "normal sync" for the sync to resume. No backup was restored on the server.

The NextCloud server has a bunch of remote smb remote storages attached to it, if that's relevant.

There are reports that downgrading the client (https://central.owncloud.org/t/a-backup-was-restored-on-the-server/3446/8) or upgrading the client (https://central.owncloud.org/t/owncloud-backup-detected-on-external-cifs-share/4621/9) fixes the issue.

Can I just use the nightly build of the Owncloud client or will this break something with Nextcloud? Or are there plans to upgrade the NextCloud client to match the version 2.3 of the Owncloud client in the near future?

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
