### ISSUE TITLE
Missing AppStream metadata

### ISSUE THREAD

**Issue by Sesivany** [nextcloud/client_theming#66]
It'd be great if the Nextcloud client shipped AppStream metadata so that it can be nicely integrated in Linux app catalogs (GNOME Software, KDE Discover,...). I'm filing it here because it's part of branding/theming.
You can find more about the standard here: https://www.freedesktop.org/software/appstream/docs/

In Fedora, Nautilus and Doplhin integration is shipped in separate packages. I'm not sure what the upstream preferred way to ship them, but if separately, they would deserve AppStream addon metadata: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Addon.html
Then they will be listed as addons in the profile of the desktop client.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
