### ISSUE TITLE
Feature request: Run the Client as a Windows service

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/client_theming#67]
Hi!

**My current situation:** I run a home server (Windows Server 2016) which is the only machine where the NC client is installed on my local network. This is the only machine I use to do an auto sync. The server then passes all these files to other machines in the network (Windows shares).
The server runs headless with no user logon (I only do log in when working on the server).

**Problem:** The sync is only started when a user logs on the server machine. I think this could lead to sync problems (e.g. no logon on server, files get changed on the web UI of NC and also through the shares from within the network; then a user logs in on the server -> which file version will be synced then? Obviously the last changes will win, so eventually there will be data loss).

**Feature request:** It would be great if there would be an option to run the sync as a Windows (system) service. This way, the sync will always take place immediately when some files have changed (even if no user is logged in on the server).

**Comment by MOWS3944** [comment]
+1 to add an option to run the sync as a Windows (system) service

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!

**Comment by xrkolovos** [comment]
+1. it would be very nice feature so you can run it in a server

**Comment by enoch85** [comment]
This is still related to the ownCloud client. Please read my previous post:

> Is this issue related to the ownCloud client, (thus not an theming isssue) please close it and report the issue here instead.

This is also shown when creating a new message: 

> **IMPORTANT NOTICE:**
This repository is for reporting theming and packaging issues with the Nextcloud client. The Nextcloud client is mearly a themed version of the ownCloud client so please report all **not** theming and packaging related issues at the moment to https://github.com/owncloud/client

**Comment by DecaTec** [comment]
See https://github.com/owncloud/client/issues/1581
