### ISSUE TITLE
Quota Exceed with chunk parallel uploads

### ISSUE THREAD

**Issue by daorte** [nextcloud/client_theming#7]
This issue is inherited from OC
### Steps to reproduce
1. Limit the disk quota for user "test" to 45MB
2. Put 3 files of 42MB in synced desktop folder
3. The chunk size should be the default, 10MB
### Actual behaviour
1. The Desktop application starts the upload of the 3 files simultaneously in chunked pieces of 10MB
2. The Desktop application takes one chunk of each file to upload
3. The server validates the oc-content-lenght of each chunk of each file against the free space and all three are valids
4. When one of the files ends its own upload (last chuck processed) the available quota is updated and then the other two files are rejected with InsufficientStorageException, but at this point, the desktop application sents a lot of chunked pieces of the rejected files, consuming resources for failed uploads.
5. If two or more files **sends its last chunk at the exact same time**, they can exceed the quota and get uploaded completely.
6. Extrapolates this situation for a 10GB user quota and 3 files of 9.8GB each, is a lot of resources wasted for failing uploads, or worse, the client can exeed the quota on 9.8GB

**Comment by nickvergessen** [comment]
Please discuss any issue that is not theming related in https://github.com/owncloud/client
