### ISSUE TITLE
Desktop Client - Multiple Address for Synchronisation at Home

### ISSUE THREAD

**Issue by weilbith** [nextcloud/client_theming#70]
Hey there!

I'm running _Nextcloud_ on my private server at home. For this I use a dynamic DNS address because I don't want to pay for a static one. Everything works fine, but when I'm at home in my network it is much faster to use the internal IP address to communicate with the server and not depending on the slow upload rate. The most time it doesn't really matter, but when synchronize huge directories (for example I'd like to start sync my whole music collection now) it is really annoying. For this I tried to add the same _Nextcloud_ user twice with different server address (the dynamic and the internal network one). The problem is, that I can not use the same folder to synchronize.

### Expected behaviour
It should be possible to add a second address to the same profile. The user can mark a address as the preferred one. Allays when the client connects to the server, it try at first the preferred address and if it is not working, it use the second one. 

### Actual behaviour
Just one address is admitted to define for a user profile. A second profile with the same user but another address can not be synchronized to the same folder. This caused to use the client the slow upload rate, when the devices could communicate directly trough the home network.

### Steps to reproduce
1. Open desktop client 
2. Add new profile
3. Enter home network address
4. Try to choose the same folder that is in usage by the other profile 

### Server configuration
Operating system: Ubuntu 16.04.1 LTS (build by ARMbian)
Web server: nginx/1.10.0 (Ubuntu)
Database: 10.0.29-MariaDB-0ubuntu0.16.04.1
PHP version:PHP 7.0.13-0ubuntu0.16.04.1
nextCloud version: 11.0.1 (stable)

### Client configuration
Client version: 2.2.4
Operating system: 11.0.1 (stable)
OS language: German
Qt version used by client package (Linux only, see also Settings dialog): 5.5.1
Client package (From ownCloud or distro) (Linux only): this repository

**Comment by palto42** [comment]
I like the idea, but I assume that such feature requests need to be raised for the original [ownCloud client](https://github.com/owncloud/client/) since this is only for theming and not a fork.

**Comment by weilbith** [comment]
Oh, I fought this is the fork from the OwnCloud client and all further issues directed to NextCloud will be deployed here.
So you would commend to simply copy this issue from here to the OwnCloud client repository?

**Comment by palto42** [comment]
I searched the OC client issue list and found that there are already a requests for this feature: 
[Pick different oC server hostname/IP depending on network (inside LAN vs on internet)](https://github.com/owncloud/client/issues/203) and
[Alternate server address when connected through home local network](https://github.com/owncloud/client/issues/5506) 
I have not reviewed them in full detail, but they seem to cover what you proposed.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
