### ISSUE TITLE
Local Backup detected error

### ISSUE THREAD

**Issue by Dark-Schnitzel** [nextcloud/client_theming#72]
using Client 2.2.4 build 2 on Windows 8, recent Version from the Website

Ignored Files arent touched, fresh install.

example: 
/Customer/folder/a
and 15 others synced.

This Message repeats every few minutes with keeping local backup, using normal synchronisation seems to ignore this. But there was no backup or changes from this data. another Client on Windowsn 10 with access to this Folder isnt getting any backup warning. Can it be a Problem with the last changed date?

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
