### ISSUE TITLE
share  locking share with ...

### ISSUE THREAD

**Issue by we-sell-bags** [nextcloud/client_theming#78]
osx
client  2.2.4.1

install client, go to a file you want to share

bring up the  window  "next cloud sharing" where you enter the users.

If you attempt to enter your own name you get an error  "cannot share with yourself"

fair enough..... , but after that the   "share with" box is greyed out and locked....
you cannot enter another users name.

you have to re-nagivate out of the box back to the folder and attempt to reshare again...

Seems a bit harsh.

![broken_client](https://cloud.githubusercontent.com/assets/25189116/23007727/7170eaa2-f445-11e6-8ec7-a6b487cb345d.jpg)

**Comment by enoch85** [comment]
Have you reported this to ownCloud?

**Comment by we-sell-bags** [comment]
is this not the place to report client issues?

**Comment by enoch85** [comment]
This repo is just a theming repo for the ownCloud client, so in other words is this a theming issue? No? Ok, then it belongs in the ownCloud repo. :)

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
