### ISSUE TITLE
There is ownCloud logo in crash report window

### ISSUE THREAD

**Issue by vpecinka** [nextcloud/client_theming#79]
When the desktop client crashes the report window appears. It contains ownCloud logo instead of Nextcloud.

client: 2.2.4 (build 1), macOS.

**Comment by oparoz** [comment]
Still there on 2.3 beta @rullzer @LukasReschke

**Comment by rullzer** [comment]
Well the bug reports are send to them. The only thing we could do is remove it all together.

**Comment by enoch85** [comment]
@rullzer I vote leave it in. Better to have crash reports so that errors can be fixed.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
