### ISSUE TITLE
owncloud client 2.3.0 source code has fixed issues with unity-panel-service memory leak and CPU usage

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/client_theming#81]
FYI
please update relevant nextcloud code.

**Comment by tflidd** [comment]
Yes, would be great to see an upgrade here as well, OC client 2.3.0 was released this week (https://owncloud.org/blog/new-desktop-client-2-3-0-release-out-now/). Hopefully other bugs such as the MacOS cipher problems will be solved (https://github.com/nextcloud/client_theming/issues/13) as well.

@LukasReschke what are the plans to release the new version? Do you want to release a release candidate first (perhaps as testpilot client)?

**Comment by enoch85** [comment]
FYI: https://github.com/nextcloud/client_theming/commit/79db8c9cca6eaefac4f93c7d21d62e8cb22ad0ca

**Comment by hanzei** [comment]
See #93
