### ISSUE TITLE
Help button doesn't work

### ISSUE THREAD

**Issue by aleixpol** [nextcloud/client_theming#82]
It opens this URL: https://docs.nextcloud.com/desktop/2.2/

**Comment by pixolin** [comment]
Same applies for  2.3.0rc1 (build 4) (Mac).

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
