### ISSUE TITLE
Linux Client : Indicator Applet in the wrong place.

### ISSUE THREAD

**Issue by ghost** [nextcloud/client_theming#84]
The indicator applet in Ubuntu should be on the right side. Actually, it is found on the left side, laying over the window buttons. This issue is known from the owncloud client: https://github.com/owncloud/client/issues/5432
It was fixed, I think it was a problem with Qt.

```
uname -a
Linux Ubuntu 4.4.0-63-generic #84~14.04.2-Ubuntu SMP Mon Feb 13 11:04:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
```
nextcloud --version
Nextcloud version 2.2.4
Using Qt 5.2.1

```
I compiled the Nextcloud client on my own:
```
sudo apt-get install libsqlite3-dev qt5-default libqt5webkit5-dev qt5keychain-dev libssl-dev realpath
git clone https://github.com/nextcloud/client_theming.git
cd client_theming
git submodule update --init
cd client
git submodule update --init
cd ..
mkdir build-linux
cd build-linux
cmake -D OEM_THEME_DIR=$(realpath ../nextcloudtheme)  ../client
make
sudo make install
echo 'echo "/usr/local/lib/x86_64-linux-gnu" >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf' | sudo -s
sudo ldconfig

```
Thank you,

Franz

**Comment by enoch85** [comment]
@franzhartwig Can you please make a PR to correct the issue?

**Comment by ghost** [comment]
@enoch85 I cannot make a PR, because I have made no changes to pull. I described what I have done: I cloned the Repo, I compiled the client, I installed it. Then the issue showed up as described. I have no idea how to fix it on my own.

**Comment by enoch85** [comment]
@franzhartwig This seems more like an Ubuntu issue than a client issue to me. We use ownClouds client and theme it, so if there's an issue with the client itself this should be reported to the ownCloud repo. 

And looking at the issue on ownCloud, this seems to be fixed. But what you are stating is that it's wrong on Nextcloud?

**Comment by ghost** [comment]
@enoch85 The ownCloud client affected by the bug used Qt 5.2.x. The fixed version uses Qt 4.8.6.

The Nextcloud client uses Qt 5.2.1. I think this is the problem. Is it possible to compile the client to use Qt 4.8.6?

**Comment by enoch85** [comment]
Hmm... I don't know. Maybe @ivaradi knows?

**Comment by ivaradi** [comment]
The client can be compiled with Qt4, and this is how the package in the PPA is built. (Maybe @franzhartwig   you could use those packages...)

I think the simplest way to achieve this is to have the Qt4 development libraries installed but notf the Qt5 ones. However, based on the sources, it seems that if you set the ``BUILD_WITH_QT4`` cmake variable to ``ON`` (e.g. ``cmake -DBUILD_WITH_QT4=ON``), it makes sure to build with Qt4.

**Comment by ghost** [comment]
Of course, I could use the PPA. But you asked for testing Version 2.3.0: https://help.nextcloud.com/t/help-testing-the-2-3-0-desktop-client-beta/8932 - is there a PPA for this version?

I compiled with the suggested cmake setting:
```
-- Search for Qt5 was disabled by option BUILD_WITH_QT4
-- Could not find Qt5, searching for Qt4 instead...
...
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.6", minimum required is "4.7.0")
-- If possible compile me with Qt 5.4 or higher.
...
  By not providing "FindKF5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5", but
  CMake did not find one.

  Could not find a package configuration file provided by "KF5" (requested
  version 5.16) with any of the following names:

    KF5Config.cmake
    kf5-config.cmake
...
```
Seems to be o.k. It should work without kf5.  I will test the client this evening (actually connected via SSH and CLI to the machine ...).

**Comment by ghost** [comment]
Compiling with qt 4.8.6 works:
```
nextcloud --version
Nextcloud version 2.2.4
Using Qt 4.8.6
```
The indicator applet is at the right place, now. Thanks.

@ivaradi I tested the nextcloud version in your PPA some time ago. There was an error, unmet dependencies with libqt5keychain0.
```
uname -a
Linux Ubuntu 4.4.0-64-generic #85~14.04.1-Ubuntu SMP Mon Feb 20 12:10:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ivaradi** [comment]
@franzhartwig that must have been some really old version. The qtkeychain library is also built in the PPA, and that is what the client package depends on.

**Comment by enoch85** [comment]
@franzhartwig So is this still an issue? Please close otherwise. :)
