### ISSUE TITLE
Failed to connect with owncloud in url

### ISSUE THREAD

**Issue by fabiankessler** [nextcloud/client_theming#85]
Installed Windows client from https://nextcloud.com/install/#install-clients (website says 2.2.4, Windows gui does not say version number).

Entered url in the form https://my.domain.com

Getting red error message: 

> Failed to connect to Nextcloud at https://my.domain.com/owncloud/status.php: error downloading https://my.domain.com/owncloud/status.php - server replied: Not Found

Same with http. The correct url would be with nextcloud, not owncloud. 

Shouldn't that have been changed by now? Did the site give me an old version? What can I do to tell the Windows program the correct url? Or do I need a hack on the server to map that url to the new one?

It's a show stopper.

**Comment by fabiankessler** [comment]
It's Nextcloud-2.2.4.2-setup.exe

Nextcloud is version 11, that's what the VM install scripts gave me: Nextcloud 11.0.1 (stable)

**Comment by fabiankessler** [comment]
I worked around this by disabling the /etc/apache2/sites-available/000-default.conf on my VM, and in /etc/apache2/sites-available/nextcloud_http_domain_self_signed.conf after

> Alias /nextcloud "/var/www/nextcloud/"

I have added

> Alias /owncloud "/var/www/nextcloud/"

Now the Windows client can connect and synchronize.

**Comment by fabiankessler** [comment]
No reason?

**Comment by enoch85** [comment]
@fabiankessler 

> I have added
Alias /owncloud "/var/www/nextcloud/"

It was obliviously a configuration error on your end, or there is something wrong in the VM. Please post an issue there and I'll have a look.
