### ISSUE TITLE
Building on Debian 9

### ISSUE THREAD

**Issue by Pablohn26** [nextcloud/client_theming#87]
Since I have had two problems that are not documented but are fixed on issues, I write here the steps to build Nextcloud client on Debian 9 as reference or as content to move somewhere.

Since [Ubuntu ppa](https://github.com/nextcloud/client_theming#installing-on-ubuntu) does not provide packages with good dependencies, you need to build from the source. The steps are:

Install required packages. 

    sudo apt-get install git libsqlite3-dev qt5-default libqt5webkit5-dev qt5keychain-dev libssl1.0-dev cmake build-essential libowncloudsync0

If you are using Debian 9 install libssl1.0-dev  (due to #68)

    sudo apt-get install libssl1.0-dev 

If you are using Debian 8 install libssl-dev

    sudo apt-get install libssl-dev

Clone source code

    git clone https://github.com/nextcloud/client_theming.git

Go to source code folder

    cd client_theming

Update submodules

    git submodule update --init --recursive

Create build folder

    mkdir build-linux

Go to build-linux

    cd build-linux

Run cmake (customized to fix #15) 

    cmake -D OEM_THEME_DIR=$(realpath ../nextcloudtheme) -DCMAKE_INSTALL_PREFIX=/usr  ../client

Build it

    make

And install it (if you want)

    sudo make install

I guess just copy pasting shoud work.  Could somebody confirm it? 

The problem is I do not know where to add specific instructions for this distribution. So I write it here and feel free to copy paste or link. 

At any time we should address each distro build, for each distribution . It is not a fix for #32 , but could help for users of distros without packages (for example debian, or ubuntu #48 ). I know a source build is not the same than a package, but at least it is a start.

**Comment by enoch85** [comment]
Can you please add these steps in the README @Pablohn26?
