### ISSUE TITLE
client uses lots of System Resources

### ISSUE THREAD

**Issue by holzfelix** [nextcloud/client_theming#91]
The updater app for windows uses too much resourses. Is there a way to reduce the amount of system resources?

I'm using windows 10 64bit professional, i7 6200 and 16GB ram. When app is in sync mode the whole system is unusable.

Already tried to reinstall the app.

**Comment by enoch85** [comment]
Please report these kind of errors to the [ownCloud client repo](https://github.com/owncloud/client) as this is just the theming repo.

Thanks!
