### ISSUE TITLE
Snap packages builds with absolute /snap prefix which is not guaranteed to work

### ISSUE THREAD

**Issue by 3v1n0** [nextcloud/client_theming#95]
See this comment by @kyrofa: https://github.com/nextcloud/client_theming/pull/77#issuecomment-284541717

$SNAP could be different from /snap/<snap-name>/current and we should support that when building

**Comment by 3v1n0** [comment]
This is going to be fixed with `snapcraft-preload` once https://github.com/sergiusens/snapcraft-preload/pull/5 is merged

**Comment by enoch85** [comment]
> This is going to be fixed with snapcraft-preload once sergiusens/snapcraft-preload#5 is merged

Is merged --> closing
