### ISSUE TITLE
NextCloud overlay icon on files/folders is empty.

### ISSUE THREAD

**Issue by cyclops1982** [nextcloud/client_theming#97]
I've moved from OwnCloud to NextCloud.
This means i uninstalled the client and installed nextcloud.

Now, my files/folders that are synced look like this:
![nextcloudissue](https://cloud.githubusercontent.com/assets/853569/23711216/85247b60-041f-11e7-8a38-36dcbcb8d6bb.PNG)

The folders 'Stuff', 'QNotes' and 'Clients' is synced.

**Comment by enoch85** [comment]
Duplicate https://github.com/nextcloud/client_theming/issues/5
