### ISSUE TITLE
certificate info lists the CA twice

### ISSUE THREAD

**Issue by tessus** [nextcloud/client_theming#98]
Version 2.3.0rc1 (build 4)

This is not exactly a theming issue, but the problem does not occur on the latest owncloud client (2.3.0 (build 4097)).

As you can see in the screenshot below, the Certificate Authority is shown twice:

![certinfo](https://cloud.githubusercontent.com/assets/223439/23828976/1fcb69ba-06b1-11e7-9e43-7dcdbaab9a29.png)

**Comment by tessus** [comment]
Also, for the final 2.3 version, please add commit https://github.com/owncloud/client/commit/4a010ce7cd60ec911ad09db105a17a319d1979be
(see https://github.com/owncloud/client/issues/5603 - certificate information display error)

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
