### ISSUE TITLE
Client doesn't connect to server: GetDYLDEntryPointWithImage failed

### ISSUE THREAD

**Issue by jlfranklin** [nextcloud/client_theming#99]
I'm not able to connect with 2.3.0.4rc1.  Looking at my server logs, the client never even attempts.  Looking at the logs on the Mac, I see this appear when I try to create the account:

```
3/12/17 9:04:28.904 AM nextcloud[12504]: GetDYLDEntryPointWithImage(/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit,_NSCreateAppKitServicesMenu) failed.
```

The same account works fine with the ownCloud client, suggesting this is a build issue with the NextCloud client.

MacOS: 10.11.6 (15G1217)
NextCloud dekstop: 2.3.0.4rc1
NextCloud server: 11.0.1

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
